### ISSUE TITLE
Persist and automatically retrieve the `config-repo` value for add, delete, install and upgrade operations

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1271]
Follow up from https://github.com/weaveworks/weave-gitops/issues/1128

As a weave gitops user I want to be able to add application automation to the correct configuration repo for my cluster without having to know and specify on each application command so that commands are simpler, shorter and less likely to cause issues.

**Acceptance criteria**
- [ ] Initial running of `gitops install --config repo <repo>` to install Weave GitOps on a new cluster 'sets' the value for config repo in a way which can be subsequently retrieved.
- [ ] Running `gitops install` to upgrade should not require a `--config-repo` flag and instead use the value set in the initial install. 
The above changes may require additional changes where install needs to check for existing install/config-repo value in the cluster and provide the appropriate messages. Scenarios I can think of:
- No existing WGO install, no config-repo flag provided: message saying that a value is required
- Existing WGO install, no config-repo flag provided: (verbose only?) message saying found WGO/Flux versions <xyz> and config repo <repo>. Performing update to (optional) WGO/Flux versions <x1y1z1>
- Existing WGO install, config-repo value provided, matches known cluster value: as above
- Existing WGO install, config-repo value provided, different to known cluster value: Warning/Confirmation on mismatch and that this will remove applications from <cluster-config-repo>, do you want to continue (y/N)
- [ ] Running `gitops add app` would use the known cluster value as default, this could be overwritten by the flag with no warning necessary.
- [ ] Running `gitops delete app` would use the known cluster value as default, this could be overwritten by the flag with no warning necessary.
- [ ] Running `gitops upgrade` uses the known cluster value and cannot be overwritten with a flag. It should fail if no value is detected.

**Comment by JamWils** [comment]
We should just put a label on the CRD itself.

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-github-gitops-repo-000
  namespace: wego-system
  labels:
    gitops.weave.works/config-repo: true
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: wego-github-gitops-repo-000
  url: ssh://git@github.com/jamwils/gitops-repo-000.git
```
