### ISSUE TITLE
Use path param in the add command

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#142]
**Short description**
As an application operator, I want to use the path param in the `add` command so that I can specify the manifests directory in the repo.

**Acceptance criteria**
**Given**: that I have a wego installed and running into a cluster
**When**: I run the `wego add . --path ./kustomize`
**Then**: a `Kustomization` resource will be created with the `path` field specified.

**Given**: that I have a wego installed and running into a cluster
**When**: I run the `wego add . --path  ./charts/podinfo --deployment-type helm`
**Then**: a `HelmRelease` resource will be created with the `chart` field specified.

**Design materials**
**Kustomize example:**
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  validation: client
```

**Helm example:**
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
  interval: 5m0s
```
