### ISSUE TITLE
Kustomization yaml file has the path as metadata.name

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#151]
**Describe the bug**
Kustomize manifest does not have the right value for name in metadata. It seems it is using the path instead.

**Expected behavior**
A repo name should be in metadata.Name field

**Screenshots**
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ./
  namespace: wego-system
spec:
  interval: 5m0s
  path: ./k3d-wego-add-app-wego-tmp-dir741533447
  prune: true
  sourceRef:
    kind: GitRepository
    name: k3d-wego-add-app-wego-tmp-dir741533447
  validation: client
```
