### ISSUE TITLE
Bug: Unable to view Flux Runtime information

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1580]
<img width="1424" alt="Screenshot 2022-03-03 at 11 32 16" src="https://user-images.githubusercontent.com/19860021/156556892-f4473278-cb9d-423f-a53a-c7dc4fbaa1a0.png">

Steps to reproduce:

- kind create cluster
- flux bootstrap
- Installed via:
```
kubectl apply -n flux-system -f - << EOF
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: jlw-helm-patch
  secretRef:
    name: flux-system
  url: ssh://git@github.com/weaveworks/weave-gitops
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
EOF
```
and

```
kubectl apply -n flux-system -f - << EOF
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/weave-gitops
      sourceRef:
        kind: GitRepository
        name: ww-gitops
  values:
    image: v2-preview
  interval: 1m0s
EOF
```
