### ISSUE TITLE
Spike: can we use kube types `protobuf` annotations to generate our types (instead of maintaining them manually)?

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1639]

**Comment by yitsushi** [comment]
Summary what I have:

1. A new [git repo](https://github.com/yitsushi/k8s-buf) to build k8s proto into a [buf.build](https://buf.build/efertone/k8s/docs) repo.
2. A working [experimental prototype repo](https://github.com/yitsushi/embed-k8s-proto-experiment) using that buf.build repo.

That way we can add the k8s resources as a `buf` dependency:
```yaml
version: v1beta1
name: buf.build/weaveworks/experiment
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/efertone/k8s
build:
  roots:
    - ./
lint:
  except:
    # allow the proto file to be in a non-package directory structure.
    - PACKAGE_DIRECTORY_MATCH
    - PACKAGE_SAME_DIRECTORY
```

Use k8s resources in our messages:

```protobuf
syntax = "proto3";

package core.v1;

option go_package = "experiment/api/core";

import "k8s.io/api/core/v1/generated.proto";

service Core {
    rpc ListNamespaces(ListNamespacesRequest) returns (ListNamespacesResponse) {}
}

message ListNamespacesRequest {}

message ListNamespacesResponse {
  repeated k8s.io.api.core.v1.Namespace namespaces = 1;
}
```

And finally, use k8s resources in out api endpoints (dummy version):
```go
package main

import (
	"fmt"

	v1 "k8s.io/api/core/v1"

	pb "experiment/api/core"
)

func main() {
	ns := v1.Namespace{}
	ns.SetName("something")

	resp := pb.ListNamespacesResponse{
		Namespaces: []*v1.Namespace{
			&ns,
		},
	}

	fmt.Printf("%+v", resp)
}
```

Output:
```
❯ go run ./core/api
{state:{NoUnkeyedLiterals:{} DoNotCompare:[] DoNotCopy:[] atomicMessageInfo:<nil>} sizeCache:0 unknownFields:[] Namespaces:[&Namespace{ObjectMeta:{something      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:NamespaceSpec{Finalizers:[],},Status:NamespaceStatus{Phase:,Conditions:[]NamespaceCondition{},},}]}
```
