### ISSUE TITLE
Return a list of namespaces that a user can access

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1725]
Part of #1725

We want to show GitOps resources across namespaces. Given how RBAC works in kubernetes, we need to know which namespaces to query.

We determine "access" as a user who has these permissions in a given namespace:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wego-admin-user-role
  namespace: {{.Values.namespace}}
rules:
  - apiGroups: [""]
    resources: ["secrets", "pods","events", "namespaces"]
    verbs: [ "get", "list" ]
  - apiGroups: ["apps"]
    resources: [ "deployments", "replicasets", "pods" ]
    verbs: [ "get", "list" ]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: [ "kustomizations" ]
    verbs: [ "get", "list" ]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: [ "helmreleases" ]
    verbs: [ "get", "list" ]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories" ]
    verbs: [ "get", "list" ]
```

Acceptance Criteria:
* Some function or `interface` needs to return a list of namespaces that represent "access" for a given user

Reference PoC PR: https://github.com/weaveworks/weave-gitops/pull/1715
