### ISSUE TITLE
Reconciled objects not appearing in a helm release

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1833]
Given this helm release:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  releaseName: gitops-server
  targetNamespace: flux-system
  chart:
    spec:
      chart: ./charts/gitops-server
      sourceRef:
        kind: GitRepository
        name: ww-gitops
  install:
    remediation:
      retries: 3
  values:
    namespace: flux-system
    additionalArgs: ["--insecure"]
    image:
      tag: v0.7.0-rc6
      repository: ghcr.io/weaveworks/wego-app
    adminUser:
      create: true
      username: wego-admin-4242
      password: notsecure
  interval: 1m0s

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/weaveworks/weave-gitops
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/ 
```

We get this:
<img width="1741" alt="Screen Shot 2022-03-29 at 11 56 29 AM" src="https://user-images.githubusercontent.com/2802257/160675642-2cb99c83-c190-42e8-9513-4d0dffdfa4b9.png">

Expected: we should get a lit of reconciled objects
