### ISSUE TITLE
Show container image for applications

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2032]
**Short description**
As an application operator I want to view deployed images and their version so that I can verify which revision of my applications are actually running.

### Acceptance criteria
When I go to the detail page for a Kustomization or Helm Release I will see the following behavior on the detail tab.

- Images column Application Details view which shows `imageName:tag`. When multiple container images exist, for example a sidecar, these should be one image per line in the table.
- Table columns should be in order: name, type, namespace, status, message, images
- Shows on Deployment and Pod objects

### Out of Scope
- Reconciliation Graph also shows list of images
- Text within Reconciliation Graph is selectable

**Design materials**
Example from the Flux Runtime view running on the staging cluster
<img width="2328" alt="Screenshot 2022-04-28 at 13 02 36" src="https://user-images.githubusercontent.com/19860021/165747839-8d1e3c50-4bae-4cb9-afa8-94119a24b553.png">

Example from figma, note there have been changes since this in terms of other content, but shows an example of the images column and its format.
<img width="1810" alt="Screenshot 2022-04-28 at 12 56 55" src="https://user-images.githubusercontent.com/19860021/165746876-7f16667f-c14b-4c41-bd6e-f7f7981450ef.png">

**Open questions**
- Should we expose in some way on the Applications summary view? Initially left out as feel that view already has a larger number of columns than most screens real estate will allow; additionally complicated by likely large number of images associated with a given kustomization/helmrelease
- Are there scenarios where a secondary container may exist alongside the flux controllers?
- Column reordering - above proposal is based on some user testing where the assertion was that Status is ultimately the first thing to care about so have it first. Also open to swapping Name and Status, which would be comparable to GKE console for example

**Comment by JamWils** [comment]
Per your open questions above:

1. No
2. Yes, there are cases that this could happen but none of the flux controllers do that.  I believe the controller needs to be labeled `part-of:flux`
3. I find namespace being last to be a bit odd.

**Comment by sympatheticmoose** [comment]
@JamWils I understand your point on namespace having spoken, that it does 'pair' more with name/type, and is valuable upfront given scenarios where failing components in a dev environment are less worrying. 

Status and message similarly 'pair' in my mind, so I'm thinking in groups:
- [name, type, namespace, images] - identifiers
- [status, message] - status

Current implementation is: name, type, namespace, status, message. It still feels wrong having status so far along, which was my primary reason for wanting to reorder generally. So two other options:

A) status, message, name, type, namespace, images (keep in groups)
B) status, name, type, namespace, images, message (break groups, message at the end still feels a relatively common pattern)

**Comment by yitsushi** [comment]
From HelmReleases this information is not available without extra queries in the background for resources with `app.kubernetes.io/managed-by: Helm` and `app.kubernetes.io/instance: cert-manager` labels. At least I couldn't find them. Do we want to make those extra queries? That means we have to query known resources types like pod, service, deployment (?) and return with the list.

 - HelmRelease contains only reference to the chart and the provided Values, but that object has arbitrary structure.
 - HelmChart contains info about the chart, but not about their values (so like where to download from)

**Comment by JamWils** [comment]
I thought that Flux would attach lables for the applicable helm release.  So you should be able to query the labels on the deployment for the particular helm release @yitsushi

**Comment by JamWils** [comment]
@yitsushi here is a snapshot of the labels for the gitops-server.  You can see the labels that tie it to the helm release.

![Screen Shot 2022-05-02 at 10.37.56 AM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/c830b9b2-36fc-4714-9325-bfa350776cf9)![Screen Shot 2022-05-02 at 10.37.56 AM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/dc71cb85-619f-43b0-840e-56d895619cdc)

**Comment by yitsushi** [comment]
For deployment yes, for pods we don't have this label (my "update")

Yes on Deployment:
```
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: v1.8.0
    helm.sh/chart: cert-manager-v1.8.0
    helm.toolkit.fluxcd.io/name: cert-manager
    helm.toolkit.fluxcd.io/namespace: cert-manager
```

But a pod created by that deployment (replicaset)

```
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: v1.8.0
    helm.sh/chart: cert-manager-v1.8.0
    pod-template-hash: 76578c9687
```

The screenshot shows different resources like Pod. For Deployment we can't say "that's the image" from the deployment Spec because a deployment can have multiple pod definitions.

Or is it just Deployment  and Pod specs purely and not underlying real Pods? It's not clear what happens if a Deployment says:
I want 3 instances of Pod-A and one instance of Pod-B,

In this case:
 - Show 4 rows for each Pods
 - Show 2 rows and the desired image defined in the Deployment spec
