### ISSUE TITLE
ClusterRole for default user.

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2053]
@jpellizzari put it best:

> Now that we have some of the cross namespace stuff in there, I am a little concerned about the Day 1 experience for new users: they won't see much...Since we are using the wego-admin service account, they really only see the flux-system namespace. We should consider some type of ClusterRole for the day 1 user. Otherwise, all of our fancy graphs and "single pane of glass" story goes out the window

We should change the default user to be a cluster role so the day one experience for Weave GitOps is a pleasant one.

**Comment by aliusmiles** [comment]
Please do so! I've just installed wego following docs and can't see any of hr/kustomizations in apps' namespaces (I'm using namespace per app environment and putting hr/ks to each namespace to keep the same names and to avoid clutter in flux-system namespace)

Any suggestions on what to change to grant admin user permissions to all namespaces with v0.8.0, chart v2.0.2 ?

**Comment by sympatheticmoose** [comment]
Hi @aliusmiles - based on https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/templates/admin-user.yaml, updating the Role/RoleBinding to ClusterRole/ClusterRoleBinding worked for me.

Here's alltheyaml as an example:

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.gitops.weave.works

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1m0s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wego-test-user-read-resources
  namespace: flux-system
subjects:
  - kind: User
    name: wego-admin
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: wego-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wego-admin-role
  namespace: flux-system
rules:
  - apiGroups: [""]
    resources: ["secrets", "pods" ]
    verbs: [ "get", "list" ]
  - apiGroups: ["apps"]
    resources: [ "deployments", "replicasets"]
    verbs: [ "get", "list" ]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: [ "kustomizations" ]
    verbs: [ "get", "list", "patch" ]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: [ "helmreleases" ]
    verbs: [ "get", "list", "patch" ]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories" ]
    verbs: [ "get", "list", "patch" ]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]
```

To configure the admin password I then generated the secret with a hashed password as described here https://docs.gitops.weave.works/docs/configuration/securing-access-to-the-dashboard/#login-via-a-cluster-user-account 

We will get this added shortly and also update the RBAC docs on the above page, thanks
