### ISSUE TITLE
Build multiarch container images

### ISSUE THREAD

**Issue by aliusmiles** [weaveworks/weave-gitops#2055]
**Short description**
As a wego user I want to run it on arm nodes so that I can keep all my system services and possible even whole cluster on arm arch.

**Acceptance criteria**
- [ ] release workflow produces multiarch container images

At a first glance it should be fairly easy to convert release workflow to produce multiarch images, something like https://github.com/fluxcd/kustomize-controller/blob/main/.github/workflows/release.yml. Though additional changes might be required, like to Makefile?

I'm happy to assist with testing arm images.

**Comment by makkes** [comment]
I just [built a multi-arch image](https://hub.docker.com/layers/wego-app/makkes/wego-app/v0.9.0/images/sha256-63608de1bc1d6033efd63b7d82a3d7c82505118243f1907f9eadc594baf93f7d?context=explore) today and the only thing it took me was to use buildx with the `--platform` flag. 🥳 The only caveat is that the `--load` flag doesn't work with multi-arch images so you can't easily build them locally without publishing them.

**Comment by grglzrv** [comment]
that's great, good news, to be honest yesterday i built it as well for arm/v7 (Rasp Pi 4 - 4GB) and arm64 (Rasp Pi 4 - 8GB)

https://hub.docker.com/repository/docker/lazarovg/wego-app/tags?page=1&ordering=last_updated


yeah you may use cache docker layers to build it in your workflow

for example:

```
     # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      # Set up QEMU
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Inspect builder
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      # All Available platforms
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      # Build the images
      - name: Run Buildx 
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache-new" \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t owner/image:tag \
            --file ./Dockerfile \
            . \ 
            --push
            
      # Clean the old cache and move the new one
      - name: Clean old cache and move new cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

you may use the cache during the docker build, save the new cache, then remove the main cache and move the new cache as main cache 

```
     # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
   # Clean the old cache and move the new one
      - name: Clean old cache and move new cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```
