### ISSUE TITLE
docs/configuration/securing-access-to-the-dashboard/ is outdated

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#2057]
The newer versions ( starting with 0.7.0 of Wego Core and WGE rely on flux-system instead of wego-system.

The documentation still points to wego-system. 
The docmentation still has roles for dealing with applications. I think we can take out : 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: write-apps
subjects:
- kind: User
  name: admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: apps-writer
  apiGroup: rbac.authorization.k8s.io
```

Please provide the documentation on how to deal with RBAC.
