### ISSUE TITLE
super fast getting started

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2186]
This is an idea for users who just want to see Weave GitOps in action quickly. We could provide a quick start based on a demo repo so that the user simply needs to run `flux bootstrap` and voila. A potential downside would be the (continued) use of a non-secure password. But this would offer an alternative to the getting started guide where we gradually introduce each element to explain it, here we could get things up and running, then explain later.

The repo could contain:
# readme.md
To quickly see Weave GitOps in action:
1. Fork this repo
2. Download the [Flux CLI](https://fluxcd.io/docs/installation/#install-the-flux-cli)
3. Run:
```bash
flux bootstrap github \
  --owner=<your-username> \
  --repository=weave-gitops-demo \
  --branch=main \
  --personal
``` 

This will install Flux and Weave GitOps on to your Kubernetes cluster, as well as a sample application - [podinfo](https://github.com/stefanprodan/podinfo) - so you can explore Weave GitOps.

To access the dashboard, run:
```bash
kubectl port-forward svc/ww-gitops-weave-gitops -n flux-system 9001:9001
```

and open [http://localhost:9001/](http://localhost:9001/)

The admin user credentials have been set to:
username=`admin` 
password=`password` 

To change this, follow the guidance [here](https://docs.gitops.weave.works/docs/getting-started/#configure-access-to-the-dashboard) and update the value in ww-gitops-helmrelease.yaml

(then add some screenshots of the UI)

# ww-gitops-helmrelease.yaml
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1m0s
  values:
    adminUser:
      create: true
      passwordHash: $2a$10$ns6c.prXZVQb1Ud.RB7/2e5anzMZmjrmn5ETAU893n2gQVM5P3/aG
      username: admin
```

# ww-gitops-helmrepository.yaml
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.gitops.weave.works
```

# podinfo-source.yaml
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
```

# podinfo-kustomization.yaml
```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
```
