### ISSUE TITLE
The admin credentials secret name is hardcoded

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/weave-gitops#2237]
In https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/templates/admin-user-creds.yaml we hardcode the name of the secret, given that Helm charts should generate unique names for every release, we should change the secret metadata to conform with Helm.

Instead of:
```
apiVersion: v1
kind: Secret
metadata:
  name: cluster-user-auth
  namespace: flux-system
```

Should be:
```
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-user-auth
```

Then we need to pass the secret name to the gitops-server process so it knows which secret to look for in the same namespace where gitops-server runs .
