### ISSUE TITLE
As a user, I want to be able to distinguish which Helm Repositories are OCI registries

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2274]
[Flux v0.31.0](https://github.com/fluxcd/flux2/releases/tag/v0.31.0) introduces the ability to pull Helm charts from OCI container registries by configuring Helm repositories with `type: oci.`

This is an optional field where the values can either be `default` or `oci`, see - https://github.com/fluxcd/source-controller/blob/main/docs/spec/v1beta2/helmrepositories.md#type

I would propose that in the details header we show "Type: Default" if no value is found, or `type: default` is declared, and "Type: OCI" if `type: oci` is declared. 

The URL will be similar to oci://ghcr.io/stefanprodan/charts and we could treat similarly to SSH where we display the declared value, but the hyperlink is converted to http - see https://github.com/weaveworks/weave-gitops/pull/2012 for details. 

Can test with:

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: default
spec:
  type: oci
  interval: 5m0s
  url: oci://ghcr.io/stefanprodan/charts
```

<img width="1483" alt="Screenshot 2022-06-07 at 10 33 47" src="https://user-images.githubusercontent.com/19860021/172347860-cad2cd53-7f26-41b8-96d8-7f8b54f3e7f1.png">
