### ISSUE TITLE
Publish the helm chart to GHCR

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/weave-gitops#2300]
As a Flux user I want to install the Weave GitOps UI from GitHub Container Registry instead of using Weaveworks Helm Registry. As a cluster admin, I don't want to depend on the weave.works uptime as there is no SLA for that, instead I want to pull the charts from ghcr.io.

PS. Pushing helm charts to GHCR is an easy task, here is how podinfo does it with GH Actions:

```yaml
      - name: Publish Helm chart to GHCR
        run: |
          helm package charts/podinfo
          helm push podinfo-${{ steps.prep.outputs.VERSION }}.tgz oci://ghcr.io/stefanprodan/charts
```

I suggest that Weaveworks created a `ghcr.io/weaveworks/charts` repo to host the `weave-gitops` chart.
