### ISSUE TITLE
SPIKE: Image autoupdate and pipelines

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2331]
How can we register that a new image was uploaded?  We want to be able to open a PR without automerging it.  The image automation stuff from Flux might get us part of the way there.  What events can we hook into so a pipeline can kick-off for new image promotion?

https://fluxcd.io/docs/components/image/

1. Can we hook into the image autoupdate stuff for being notified to kick-off a new pipeline?
2. Can we just use the image auto update stuff from Flux?  Is it just a matter of producing the correct objects to tie to dev, staging, and prod?
3. Set up a generic webhook provider and alert to listen to that event.  Include those objects in the results of this spike.
4. How does this relate to #2230?  How would you trigger the first step of the Github pipeline based on the incoming event? 

# Reference Material

https://fluxcd.io/docs/guides/image-update/

Public docker repo
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: gitops-app
  namespace: flux-system
spec:
  image: jamweave/weave-gitops-test
  interval: 1m0s
```

Below I was using date and timestamp for image tags:
```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: gitops-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: gitops-app
  policy:
     numerical:
      order: asc
```

```
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: gitops-app
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: wego-github-gitops-repo-000
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: james.wilson@weave.works
        name: JamWils
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./weave-gitops/clusters/dev-cluster/system
    strategy: Setters
```
