### ISSUE TITLE
CLI command for creating GitOps Dashboard

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2414]
As a user I want a simple command that will make it really easy for me to install the GitOps Dashboard onto a cluster or generate the yaml to be used via GitOps.

The current instructions in the getting started for installing the GitOps Dashboard are:
---
### Configure access to the dashboard

For this guide we will use the cluster user, for complete documentation including how to configure an OIDC provider see the documentation here.

We will generate a bcrypt hash for your chosen password and store it as a secret in Kubernetes. There are several different ways to generate a bcrypt hash, this guide uses gitops get bcrypt-hash from our CLI.

1. Clone your git repository where Flux has been bootstrapped (you could skip this step if you performed previous steps in this doc).

```
git clone https://github.com/$GITHUB_USER/fleet-infra
cd fleet-infra
```

2. Generate the password using a golang image:

```
PASSWORD="<your password>"
docker run -it --rm golang:1.17 bash -c "go install github.com/bitnami/bcrypt-cli@v1.0.2 2> /dev/null && echo -n '$PASSWORD' | bcrypt-cli"
$2a$10$OS5NJmPNEb13UgTOSKnMxOWlmS7mlxX77hv4yAiISvZ71Dc7IuN3q
```

3. Save this [bcrypt-hash](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Password_Storage_Cheat_Sheet.md) in a values file:
```yaml title="./weave-gitops-values.yaml"
adminUser:
  create: true
  username: admin
  passwordHash: $2a$10$OS5NJmPNEb13UgTOSKnMxOWlmS7mlxX77hv4yAiISvZ71Dc7IuN3q
```

:::info
Storing a hash of a password is relatively safe for demo and testing purposes but it is recommend that you look at more secure methods of storing secrets (such as [Flux's SOPS integration](https://fluxcd.io/docs/guides/mozilla-sops/)) for production systems.
:::

### Install Weave GitOps

Weave GitOps is installable via a Helm Chart and as such can be managed by Flux.

1. Clone your git repository where Flux has been bootstrapped.

```
git clone https://github.com/$GITHUB_USER/fleet-infra
cd fleet-infra
```

2. Create a `HelmRepository` Source for Weave GitOps

```
flux create source helm ww-gitops \
  --url=https://helm.gitops.weave.works \
  --export > ./clusters/my-cluster/weave-gitops-source.yaml
```

The generated file should look like this:

```yaml title="./clusters/my-cluster/weave-gitops-source.yaml"
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.gitops.weave.works
```

3. Commit and push the `weave-gitops-source.yaml` to the `fleet-infra` repository

```
git add -A && git commit -m "Add Weave GitOps HelmRepository"
git push
```

4. Create a `HelmRelease` to deploy Weave GitOps

```
flux create helmrelease ww-gitops \
  --source=HelmRepository/ww-gitops \
  --chart=weave-gitops \
  --values=<path to weave-gitops-values.yaml> \
  --export > ./clusters/my-cluster/weave-gitops-helmrelease.yaml
```

5. Commit and push the `weave-gitops-helmrelease.yaml` to the `fleet-infra` repository

```
git add -A && git commit -m "Add Weave GitOps HelmRelease"
git push
```

6. Validate that Weave GitOps and Flux are installed

```
kubectl get pods -n flux-system
```
---

As you can clearly see this is a bit cumbersome and we can improve the experience drastically.  As a new user to Weave GitOps I don't want to have to jump through hoops to be able to use the GitOps Dashboard. 

We will create a new command `gitops create dashboard [name] [flags]` which will simplify the creation of the GitOps dashboard.

**Note:** this command should mimic the behavior of the Flux CLI commands such as `flux create kustomization [name] [flags]`

## Acceptance Criteria

**Optioinal Flags**
* Namespace - If present, the namespace scope for this CLI request (default "flux-system")
* Username - If present, then we create the admin user with the following username, if none is supplied then we use "default".
* Password - If present, then we create the admin user called "admin" and default to the password.

```yaml title="./clusters/my-cluster/weave-gitops-source.yaml"
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ww-gitops
  namespace: flux-system
  labels:
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: weave-gitops
    app.kubernetes.io/created-by: weave-gitops-cli
  annotations:
    metadata.weave.works/description: "This is the Weave GitOps Dashboard.  It provides a simple way to get insights into your GitOps workloads."
spec:
  interval: 60m0s
  url: https://helm.gitops.weave.works
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 60m0s
```

### New Instructions for installing Weave GitOps in the docs

When this is complete we should have the following documentation instead of what is written out above:

---
### Install Weave GitOps

For this guide we will use the cluster user, for complete documentation including how to configure an OIDC provider see the documentation here.

1. Install the Weave GitOps CLI
```
brew install weaveworks/tap/weave-gitops 
```

2. Clone your git repository where Flux has been bootstrapped.

```
git clone https://github.com/$GITHUB_USER/fleet-infra
cd fleet-infra
```

3. Run the following command which will create a `HelmRepository` and `HelmRelease` to deploy Weave GitOps

```
PASSWORD="<your password>"
gitops create dashboard ww-gitops \
  --password=$PASSWORD \
  --export > ./clusters/my-cluster/weave-gitops-dashboard.yaml
```

:::warning
This command stores a hash of a password.  While this is relatively safe for demo and testing purposes it is recommend that you look at more secure methods of storing secrets (such as [Flux's SOPS integration](https://fluxcd.io/docs/guides/mozilla-sops/)) for production systems.
:::

4. Commit and push the `weave-gitops-dashboard.yaml` to the `fleet-infra` repository

```
git add -A && git commit -m "Add Weave GitOps Dashboard"
git push
```

5. Validate that Weave GitOps and Flux are installed

```
kubectl get pods -n flux-system
```
