### ISSUE TITLE
How to configure the app and Ingress with different base path

### ISSUE THREAD

**Issue by fahlke** [weaveworks/weave-gitops#2529]
**Describe the bug**

When installing WEGO with the Helm chart, I want to expose the WebUI for local development and testing via an ingress under a different path than `/` (e.g.: `/wego`).

Currently, as far as I can see, there is no parameter or ENV var exposed to configure the application to make use of it. The only thing that is possible, is to configure the ingress resource via the Helm chart, which does not function when set to something different than `/`.

Also figured out, that there is actually a path parameter for the application that seems to be dead code. One can start the app with, for example, `--path=/wego` with no effect at all (see: [cmd/gitops-server/cmd/cmd.go#L84](https://github.com/weaveworks/weave-gitops/blob/v0.9.1/cmd/gitops-server/cmd/cmd.go#L84)).

Some other Helm charts correctly configure the application and ingress by allowing the user to change the path and route prefix. This is something I did in my local cluster with, for example, the [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) and it is working as expected (apps are reachable via the ingress). This can be achieved by setting `prometheus.prometheusSpec.routePrefix` and `prometheus.ingress.paths`.

**Environment**

- Operating System: MacOS 12.4
- Weave-Gitops Helm chart version: 2.2.5
- Weave-Gitops app version: v0.9.1
- Flux Version: 0.31.5
- Kubernetes: v1.21.12 (kind, running local)
- Kong (for ingress): 2.8

**To Reproduce**

1. have a local Kind cluster running with Kong as ingress controller
1. get the Helm charts
    ```
    helm repo add weave https://helm.gitops.weave.works
    helm repo update weave
    ```
1. deploy WEGO with the helm chart
    ```
    helm upgrade weaveworks-gitops weave/weave-gitops \
      --install \
      -n flux-system \
      -f values.yaml  # see the values that were used below in "Additional Context"
    ```
1. verify the app is running
    ```
    kubectl get deploy -n flux-system -l='app.kubernetes.io/name=weave-gitops'
    ```
1. try to open the website in a browser or use curl
    ```
    curl -I http://localhost/wego
    ```
1. wait for the backend timeout (with `HTTP/1.1 504 Gateway Time-out`). 
1. now try it with port-forwarding and do the curl again (expected response `HTTP/1.1 200 OK`)
    ```
    kubectl port-forward service/weaveworks-gitops-weave-gitops -n flux-system 9001:9001
    curl -I http://localhost:9001/wego
    ```

**Expected behavior**

When ingress path is set to `/wego` the website should be reachable. 

**Actual Behavior**

The website is not reachable and the requests time out.

**Additional Context (screenshots, logs, etc)**

Values used to deploy WEGO via the Helm chart:

```
adminUser:
  create: true
  username: admin
  # htpasswd -bnBC 10 "" 'CHANGEME' | tr -d ':\n' | sed 's/$2y/$2a/'
  passwordHash: <use the result from the command above>
ingress:
  enabled: true
  className: kong
  hosts:
  - host: localhost
    paths:
    - path: /wego
      pathType: ImplementationSpecific
```

Alternative values used (with annotations for Kong to modify the requests):

```
adminUser:
  create: true
  username: admin
  # htpasswd -bnBC 10 "" 'CHANGEME' | tr -d ':\n' | sed 's/$2y/$2a/'
  passwordHash: <use the result from the command above>
ingress:
  enabled: true
  annotations:
    konghq.com/preserve-host: "true"
    konghq.com/strip-path: "true"
  className: kong
  hosts:
  - host: localhost
    paths:
    - path: /wego
      pathType: ImplementationSpecific
```

**Comment by kaybinwang** [comment]
Just ran into this issue when setting up the dashboard under a subpath too. Are there any plans to prioritize fixing the issue?

Happy to help contribute if it's a relatively straightforward solution and if I could get some code pointers.

**Comment by danielkimuipath** [comment]
Is there an update on this?

**Comment by guilhermegouveiahr** [comment]
> @kaybinwang thank you for your offer of help!
> 
> Unfortunately, this issue is not straightforward because of the way the app is currently set up. We researched this issue earlier: configuring the backend part is not a problem, the issue is that the frontend is generated as static files and is not configurable enough to make "the app and Ingress with different base path" with the current app setup.
> 
> So, this issue will require more bandwidth for deeper research and a major rework, which we don't have right now. We'll get back to it when we have more bandwidth. We know that our users are interested in this functionality, and we keep this in our priority backlog.

Waiting eagerly for this new feature. 
Still can't provide access to my users from the internet. 
They have to port-forward.

**Comment by LappleApple** [comment]
New ask from the community: https://weave-community.slack.com/archives/C0248LVC719/p1693487267920289

**Comment by opudrovs** [comment]
Based on what I researched for this issue long ago (If nothing has changed drastically while I was away), there are technical issues with the current OSS setup which prevent it from configuring basepath dynamically.

I do not remember many details, because it was long ago and I had just started working on the product then. @ozamosi helped me with the research. But I remember that configuring backend for this was not a problem. The issue was with frontend generated as a set of static files with hardcoded paths. And it was impossible to change the paths for some reason without a major rework.

So, the current issue was put on hold while a major rework to simplify cross-product development process was being discussed and then with the new product setup we were going to revisit the issue.

I am not sure what the current state on merging the repos is, I bet there are other priorities.

**Comment by foot** [comment]
I would guess to fix this we'd have to address:

- some runtime config declaring the subpath
  - perhaps this would have to be injected into the returned index.html from some BE config?
  - Perhaps just setting a `<base />` tag?
  - I've seen a trick where an ingress controller can also inject a `<base />` tag too.
- api service: write some new injector to add this subpath as a prefix to each request
- `<BrowserRouter />` add a `basepath` prop
- Figure out how to get parcel (the FE build tool) to dynamically load assets from a subpath. From searching the parcel repo and @opudrovs' comment above, this _seems_ to be the tricky bit.

**Comment by foot** [comment]
Looks like building with `parcel --public-url ./` will make the css/js assets relative.

Combined with a `<base href="foo/" />` tag this should work.

From https://github.com/parcel-bundler/parcel/issues/9092 parcel injects some assets (link:css from my testing) at the very top of `<head>` _before_ the base tag, so can't really use that.

But if we injected a `<base />` tag ourselves in the static file handler in the golang code that would be a workaround..

**Comment by foot** [comment]
Also if anyone knows of other prior art here that would be interesting, e.g. can kube-dashboard / prometheus' UI / others? be configured under subpath?

**Comment by gre9ory** [comment]
@foot Thanks for taking the initiative!

I am willing to take any solution, however I think from the user's perspective it is the "usual" and convenient way maybe to handle the subpath configuration in the application and ingress configuration. In my experience normal configuration procedure in this scenario is:

a) let the application know the subpath it is being hosted under in some way (examples below)
b) configure ingress object (path, maybe add rewrite if required for application)

Examples:

[Grafana has these options](https://artifacthub.io/packages/helm/grafana/grafana#example-ingress-with-path) (in the helm chart):
```
grafana.ini:
  server:
    domain: monitoring.example.com
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: true
ingress:
  enabled: true
  hosts:
    - "monitoring.example.com"
  path: "/grafana"
```
or [kube-prometheus-stack using the `routePrefix` swtitches](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=values&path=prometheus.prometheusSpec.routePrefix)

```
## Prefix used to register routes, overriding externalUrl route.
## Useful for proxies that rewrite URLs.
##
routePrefix: /
```

From the PR it looks as if you are aiming to solve it another way with the headers alone. This may be dependent on individual ingress controller header support but I may be wrong about that. 

Just thinking that the users expectation may be different in terms of configuring subpaths ... but feel free to ignore this remark.

**Comment by foot** [comment]
> From the PR it looks as if you are aiming to solve it another way with the headers alone. This may be dependent on individual ingress controller header support but I may be wrong about that.

Yeah indeed, I've been thinking about it too and we wanna support all the ingress controllers.

I will change the code so we can work with a standard PrefixPath ingress resource.

- Add some `--route-prefix`
- Add some redirect at `/` to redirect to `--route-prefix` for when you're port-forwarding
- Add the `/health` under the route-prefix or keep it on the root? 🤔 both? What does prom do?

```yaml
additionalArgs:
  - --route-prefix=/foo/

ingress:
  enabled: true
  hosts:
  - host: ""
    paths:
      - path: /foo
        pathType: Prefix
```

Kind of thing?
