### ISSUE TITLE
SPIKE: Session ID suffix to resources

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2657]

**Comment by chanwit** [comment]
Outcomes:

This is possible by leveraging `kustomization.yaml`.

For example:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: test-session
commonLabels:
  gitops.weave.works/session: session-cvng7
nameSuffix: -cvng7
resources:
  - nginx.yaml
  - new/nginx-2.yaml
```

and this is the generated YAMLs:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    gitops.weave.works/session: session-cvng7
  name: nginx-cvng7
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    gitops.weave.works/session: session-cvng7
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-2
    gitops.weave.works/session: session-cvng7
  name: nginx-2-cvng7
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-2
      gitops.weave.works/session: session-cvng7
  template:
    metadata:
      labels:
        app: nginx-2
        gitops.weave.works/session: session-cvng7
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    gitops.weave.works/session: session-cvng7
  name: nginx-deployment-cvng7
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      gitops.weave.works/session: session-cvng7
  template:
    metadata:
      labels:
        app: nginx
        gitops.weave.works/session: session-cvng7
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
```

By tweaking the` kustomization.yaml` file on the fly, we would be able to suffix all resources and still use Flux's kustomize controller to manage the life-cycle of those resources.
