### ISSUE TITLE
Okta group impersonate limitation

### ISSUE THREAD

**Issue by knopka** [weaveworks/weave-gitops#2696]
**Describe the bug**

Looks like this configuration https://github.com/weaveworks/weave-gitops/tree/main/charts/gitops-server#impersonate doesn't work 
```
rbac:
  create: true
  impersonationResources: ["groups"]
  impersonationResourceNames: ["gitops-reader"]
```
I have configured login via an OIDC(Okta) provider. In Okta, group created and user added to this group. Okta Application and Authorization Server configured as well. Then I created `ClusterRole` and `ClusterRoleBinding` with subject as group name I created in Okta. Without `rbac` configuration block I mentioned above all works and I can see cluster data in UI, but after adding `rbac` configuration block UI is empty.

From Logs
```
2022-09-04T06:44:42.172Z	DEBUG	gitops.auth-server	auth/jwt.go:155	Found principal	{"user": "raman", "groups": ["wego-admin-rk"], "tokenLength": 0, "method": "*auth.JWTCookiePrincipalGetter"}
2022-09-04T06:44:42.172Z	DEBUG	gitops.auth-server	auth/jwt.go:155	Found principal	{"user": "raman", "groups": ["wego-admin-rk"], "tokenLength": 0, "method": "*auth.JWTCookiePrincipalGetter"}
2022-09-04T06:44:42.194Z	ERROR	gitops	clustersmngr/factory.go:367	failed filtering namespaces	{"cluster": "Default", "user": "raman", "error": "user namespace access: users \"raman\" is forbidden: User \"system:serviceaccount:flux-system:ww-gitops-weave-gitops\" cannot impersonate resource \"users\" in API group \"\" at the cluster scope"}
```

**Environment**

- Weave-Gitops Version - helm chart version - 3.0.3
- Flux Version - v0.31.2
- Kubernetes version - v1.21.14-eks-18ef993

**To Reproduce**

1. Configure Okta (User, Group, Application and Authorization Server)
2. Create `ClusterRole` and `ClusterRoleBinding` with subject as group name created in Okta.
3. Add configuration below:
```
rbac:
  create: true
  impersonationResources: ["groups"]
  impersonationResourceNames: ["some-group"]
```

**Expected behavior**
After adding  `rbac` configuration block impersonate limitation works and in UI we can see cluster data.

**Actual Behavior**
After adding  `rbac` configuration block with specific group in UI there is no cluster data.

**Comment by cr1cr1** [comment]
```
impersonationResourceNames: []
```

does not throw the error, but still nothing is displayed in the UI

**Comment by LukaszRacon** [comment]
Two issues:
- impersonation for `groups` requires access to `impersonate` on `users` resource at cluster scope level (overall bad idea) 
- `impersonationResourceNames: ["gitops-reader"]` does not match group in logs `"groups": ["wego-admin-rk"]`

Following config requires access to `impersonate` on `users` resource at cluster scope level
```
rbac:
  create: true
  impersonationResources: ["groups"]
  impersonationResourceNames: ["gitops-reader"]
```

With current configuration it fails with error:
`{"cluster": "Default", "user": "raman", "error": "user namespace access: users \"raman\" is forbidden: User \"system:serviceaccount:flux-system:ww-gitops-weave-gitops\" cannot impersonate resource \"users\" in API group \"\" at the cluster scope"}`

Here is a fix (adjust names/namespaces accordingly)
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ww-gitops-weave-gitops-patch
rules:
  - apiGroups:
      - ""
    resources:
      - users
    verbs:
      - impersonate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ww-gitops-weave-gitops-patch
subjects:
  - kind: ServiceAccount
    name: ww-gitops-weave-gitops
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ww-gitops-weave-gitops-patch
```
