### ISSUE TITLE
SPIKE: PoC of using vcluster for gitops run

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2731]
Write a tiny proof of concept of using vcluster with gitops run. 

Does it work well for what we've got there now? Is it "easy" to connect pods between the inside and outside?

**Acceptance criteria**
* Run podinfo inside vcluster
* Dashboard gets installed
* Port forwarding still works
* How would we connect the services inside and outside the vcluster?

**Comment by enekofb** [comment]
is there any issue / doc where i could see the place for vcluster within gitops run? it is for tenancy management within remote clusters?

**Comment by chanwit** [comment]
I'll write up the doc after we understand more about it.

**Comment by chanwit** [comment]
- [x] Run podinfo inside vcluster
  - [x] Dashboard gets installed
  - [x] Port forwarding still works

![Selection_035](https://user-images.githubusercontent.com/10666/190411296-bd943fb7-9a4b-4b28-a556-2a52ef59af8a.png)

**Comment by chanwit** [comment]
vcluster + GitOps Run enables Git-like parallel worlds for devs.

![image](https://user-images.githubusercontent.com/10666/190645410-3dc367fd-0258-4e3f-a905-6c30e7c90485.png)

**Comment by chanwit** [comment]
Here's the Helm values we would use as an example to do service mapping.

```
  values:
    vcluster:
      image: rancher/k3s:v1.23.5-k3s1 
    mapServices:
      fromHost: 
      - from: dockercoins/redis
        to: default/redis
      fromVirtual: 
      - from: default/rng
        to: rng
```

**From host**, there's no restriction. I was able to map a Redis service into the virtual cluster and my pod could write data to the Redis instance on the host.

What does that mean?
It means that we can develop an app in an isolation vcluster, and the app is still able to connect to, for example, an external DBMS.

**From virtual**, there is a *restriction*.
We can map a service from the virtual cluster to a service inside the namespace where we started the virtual cluster only.
