### ISSUE TITLE
The helmrelease reconcillation is failed for ww-gitops and unable to access the UI with ingress set up

### ISSUE THREAD

**Issue by eravindar12** [weaveworks/weave-gitops#2792]
I am facing the below issue with the dashboard setup. 

`flux reconcile helmrelease ww-gitops
► annotating HelmRelease ww-gitops in flux-system namespace
✔ HelmRelease annotated
◎ waiting for HelmRelease reconciliation
✗ HelmRelease reconciliation failed: install retries exhausted`

Using the below Kustomization 

`apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1h0m0s
  values:
    ingress:
      enabled: true
    hosts:
    - host: xxx-xx.xxxx.io
    ingressClassName: nginx-internal
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    path: /
    pathType: Prefix
    tls:
    - secretName: xxx-xx.xxxx.io-tls
      hosts:
      - xxx-xx.xxxx.io
    adminUser:
      create: true
      username: xxx
      passwordHash: xxxx
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/weaveworks/charts `

`k describe po ww-gitops-weave-gitops-7db7c787df-b4fdt -n flux-system
+ kubectl describe po ww-gitops-weave-gitops-7db7c787df-b4fdt -n flux-system
Name:         ww-gitops-weave-gitops-7db7c787df-b4fdt
Namespace:    flux-system
Priority:     0
Node:         gke-ecom-dev-uc1-main-d8e1d673-gj5v/10.196.16.98
Start Time:   Mon, 26 Sep 2022 15:01:05 +0000
Labels:       app.kubernetes.io/instance=ww-gitops
              app.kubernetes.io/name=weave-gitops
              pod-template-hash=7db7c787df
Annotations:  <none>
Status:       Running
IP:           100.66.13.24
IPs:
  IP:           100.66.13.24
Controlled By:  ReplicaSet/ww-gitops-weave-gitops-7db7c787df
Containers:
  weave-gitops:
    Container ID:  docker://7a04e96a20095a7dc283b14784bebe34c7afdb5954dfd53429a3ec42073e35ed
    Image:         ghcr.io/weaveworks/wego-app:v0.9.5
    Image ID:      docker-pullable://ghcr.io/weaveworks/wego-app@sha256:a4bcb924074ddedfd4dedae35937734cc71b36e8ad39ff0c558b026c1ce26c43
    Port:          9001/TCP
    Host Port:     0/TCP
    Args:
      --log-level
      info
      --insecure
    State:          Running
      Started:      Mon, 26 Sep 2022 15:01:10 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      WEAVE_GITOPS_FEATURE_TENANCY:  true
      WEAVE_GITOPS_FEATURE_CLUSTER:  false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-g8gmb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-api-access-g8gmb:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  19m                default-scheduler  Successfully assigned flux-system/ww-gitops-weave-gitops-7db7c787df-b4fdt to gke-ecom-dev-uc1-main-d8e1d673-gj5v
  Normal   Pulling    19m                kubelet            Pulling image "ghcr.io/weaveworks/wego-app:v0.9.5"
  Normal   Pulled     19m                kubelet            Successfully pulled image "ghcr.io/weaveworks/wego-app:v0.9.5" in 2.848372971s
  Normal   Created    19m                kubelet            Created container weave-gitops
  Normal   Started    19m                kubelet            Started container weave-gitops
  **Warning  Unhealthy  19m (x2 over 19m)  kubelet            Readiness probe failed: Get "http://100.66.13.24:9001/": dial tcp 100.66.13.24:9001: connect: connection refused**`

**Comment by torhagl** [comment]
I wouldn't mark this as a bug, as it's not proved to be an issue with the helm-chart itself. I answered you on Slack, but I'll re-post it here. Even though your markdown doesn't render properly I recall this issue from the error-messages.

From the [Helm chart's values-file](https://github.com/weaveworks/weave-gitops/blob/2ef84dcfc8b0d6beaea51e6edf97f9d18f8df46d/charts/gitops-server/values.yaml#L105), you need to indent the other ingress-related properties under that key. You also need to rename ingressClassName. Like so:
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1h0m0s
  values:
    ingress:
      enabled: true
      hosts:
      - host: xxx-xxx-xxx.xxxx.io
      className: nginx-internal
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      path: /
      pathType: Prefix
      tls:
      - secretName: xxx-xxx-xxx.xxxx.io-tls
        hosts:
        - xxx-xxx-xxx.xxxx.io  
    adminUser:
      create: true
      username: xxxx
      passwordHash: xxx

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/weaveworks/charts
```

If that doesn't work, I suggest you remove the ingress-stuff and try without it. Try using the gitops CLI to generate the most basic one. [Follow instructions here](https://docs.gitops.weave.works/docs/getting-started/index.html)

If it still doesn't work, please post the resulting resources generated from the HelmRelease (remove any sensitive data) here and I'll see if I can help you further.
