### ISSUE TITLE
Create Dashboard command has metadata on wrong object

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2827]
**Describe the bug**

**Environment**

- Weave-Gitops Version
- Flux Version
- Kubernetes version

**To Reproduce**

1. Run the command: `gitops create dashboard ww-gitops --password=admin --export > ./demo/dashboard.yaml`

Add the dashboard.yaml to a kustomization and push to git.

**Expected behavior**

I would expect to see metadata on the helm release page for Weave GitOps. 

```
metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides
      a simple way to get insights into your GitOps workloads.
```

I would expect to see metadata on the helm repository page for Weave GitOps. 
```
metadata.weave.works/description: This is the source location for the Weave GitOps Dashboard's helm chart. 
```

**Actual Behavior**

Instead I see the metadata on the HelmRepository object instead

**Additional Context (screenshots, logs, etc)**

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides
      a simple way to get insights into your GitOps workloads.
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://helm.gitops.weave.works
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1h0m0s
  values:
    adminUser:
      create: true
      passwordHash: keep-it-secret-keep-it-safe
      username: admin
```

**Comment by opudrovs** [comment]
It should not be a problem to move the metadata to the HelmRelease object. But I think it's not a bug it's a feature because I see metadata on HelmRepository under the acceptance criteria here?

https://github.com/weaveworks/weave-gitops/issues/2414

**Comment by opudrovs** [comment]
@JamWils should this be on the HelmRelease object?

```
metadata:
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides
      a simple way to get insights into your GitOps workloads.
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
  name: ww-gitops
  namespace: flux-system
```

and this on the HelmRepository
```
metadata:
  name: ww-gitops
  namespace: flux-system
```
or am I getting it wrong?
