### ISSUE TITLE
gitops run: race condition in setting up port forwarding

### ISSUE THREAD

**Issue by ozamosi** [weaveworks/weave-gitops#2883]
At first run, it's possible for the flux resources to be healthy and available, but for the pods not to be.

To reproduce, grab a cluster without podinfo running. Create a new directory with a file with this in it:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: dev
spec:
  interval: 1m0s
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: dev
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 1m0s
  targetNamespace: dev
```
and run gitops run as

`gitops beta run ./podinfo --no-session --port-forward namespace=dev,resource=svc/dev-podinfo,port=9898:9898`

The first run you should see `✗ Error getting pod from specMap: no running pods found for service`. Re-save the file, and it'll update and the port forwarding will work.
