### ISSUE TITLE
[UI] fluxcd-ui missing DaemonSet and MutatingWebhookConfiguration

### ISSUE THREAD

**Issue by chrislin22** [weaveworks/weave-gitops#2897]
[UI] fluxcd-ui missing DaemonSet and MutatingWebhookConfiguration

**Environment**

```
- weave-gitops-4.0.5.tgz

- flux: v0.34.0
helm-controller: v0.24.0
kustomize-controller: v0.28.0
notification-controller: v0.26.0
source-controller: v0.29.0

- Kubernetes: Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14-gke.2700"

```
**To Reproduce**
`run flux tree kustomization` show the structure 
```

├── HelmRelease/flux-system/yyy
│   ├── ConfigMap/xxx/yyy-webhook-configmap
│   ├── ConfigMap/yyy-cfg
│   ├── Service/xxx/yyy
│   ├── Deployment/xxx/yyy
│   └── MutatingWebhookConfiguration/xxx/yyy-webhook-cfg

```
```
├── HelmRelease/flux-system/xxx-validator
│   ├── ServiceAccount/platform/xxx-validator
│   ├── ClusterRole/xxx-validator
│   ├── ClusterRoleBinding/xxx-validator
│   ├── ConfigMap/platform/xxx-validator
│   └── DaemonSet/platform/xxx-validator
```
MutatingWebhookConfiguration and DaemonSet are missing from the fluxcd ui

**Comment by sympatheticmoose** [comment]
@chrislin22 many thanks for raising this - we'll take a look and try to reproduce.

**Comment by sympatheticmoose** [comment]
@chrislin22 managed to reproduce. 

Both resources are missing for the clusterrole on the admin user we create for Weave GitOps if requested. To unblock you could patch the clusterrole (available here https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/templates/admin-user-roles.yaml) to add these resources such as:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wego-admin-cluster-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "pods", "services", "namespaces", "persistentvolumes", "persistentvolumeclaims"]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: ["apps"]
    resources: [ "deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: [ "get", "list", "watch" ]
... 
(continued)
```


We'll revisit this list to check for any other missing resources.

**Comment by jpellizzari** [comment]
@sympatheticmoose We will always only support a subset of all K8s objects. Do we want to add these two objects to our subset? I don't know if there is truly a "core" set of objects; our current method for choosing objects can be described as "anecdotally popular/important".

**Comment by chrislin22** [comment]
Thanks @sympatheticmoose

**Comment by chrislin22** [comment]
Hi, thanks for the help, the `daemonSet` works now (thanks), but it doesn't work for `mutatingwebhookconfiguration` (yet), I follow the instruction to add to the `rules` as follows:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wego-admin-cluster-role
rules:
...
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - mutatingwebhookconfiguration
    verbs:
    - get
    - list
    - watch
... 
```
Anything that I was doing wrong? thanks

-cl

**Comment by sympatheticmoose** [comment]
@chrislin22 hmm, let me try and reproduce.

**Comment by sympatheticmoose** [comment]
Managed to reproduce... I have a quick fix 😅 wildcard the resources in that API group:

```
- apiGroups: ["admissionregistration.k8s.io"]
    resources: ["*"]
    verbs: [ "get", "list", "watch" ]
```

 Worked for me as shown in this screenshot.
<img width="634" alt="Screenshot 2022-11-29 at 15 28 08" src="https://user-images.githubusercontent.com/19860021/204571536-253c4dbf-c632-462e-ad4f-0be88c41b621.png">

I'm not sure why its not liking the specific resource... will keep investigating

**Comment by sympatheticmoose** [comment]
@chrislin22 got it - just needed to be plural on the resource name i.e. `mutatingwebhookconfigurations`

**Comment by chrislin22** [comment]
thanks for the quick response, I tried both the wildcard and plural, neither of them works for me (yet) - BTW, I am using fluxcd with kustomize for the cd:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1h0m0s
  values:
    adminUser:
      create: true
      passwordHash: xxxxxx
      username: xxxxxx

  postRenderers:
    # Instruct helm-controller to use built-in "kustomize" post renderer.
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              kind: Role
              name: wego-admin-role
              namespace: flux-system
            patch:
              - op: add
                path: /rules/1/resources/-
                value: "daemonsets"
              - op: add
                path: /rules/-
                value: 
                    apiGroups: ["admissionregistration.k8s.io"]
                    resources: ["mutatingwebhookconfigurations"]
                    verbs: [ "get", "list", "watch" ]
```
