### ISSUE TITLE
Support multiple instances of Flux in Flux Runtime view

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2910]
**Short description**
As a platform operator I want to see all Flux controllers on my cluster, when running multiple instances of Flux for multi-tenancy resource isolation, so that I can monitor their health and check their versions.

**Acceptance criteria**
- [ ] Flux Runtime Controller view shows controllers from multiple namespaces with the `part-of: flux` label
- [ ] New namespace column is added to the Controller tab

Reference doc: https://fluxcd.io/flux/security/best-practices/#resource-isolation

To set up a sample environment:
- run `flux install --watch-all-namespaces=false`
- then run `flux install -n <different-namespace> --watch-all-namespaces=false`

**Comment by sympatheticmoose** [comment]
re-opening whilst verifying fix

**Comment by TheGostKasper** [comment]
#### Testing scenario :
- [OSS](https://gitops.euw1.wego-gke.weave.works/flux_runtime/controllers)
   -  ##### One cluster & one flux version 
      ![image](https://user-images.githubusercontent.com/4614360/204799880-07cb1805-70ad-4b71-a30c-10aa70203571.png)


- [WGE](https://demo-01.wge.dev.weave.works/flux_runtime/flux)
  - #### multi clusters & diff flux versions
    ![image](https://user-images.githubusercontent.com/4614360/204800531-98d42e87-3476-41c3-b24f-fee9d69d6a59.png)

**Comment by sympatheticmoose** [comment]
@TheGostKasper just to be clear those screenshots above are for one instance **per cluster** and this issue is for multiple instances per cluster

**Comment by TheGostKasper** [comment]
@sympatheticmoose  i can't see any other versions within the response in OSS, so could it be a BE issue ?

**Comment by sympatheticmoose** [comment]
most likely - It doesnt work in WGE either for multiple namespaces on same cluster

**Comment by TheGostKasper** [comment]
@enekofb 

![image.png](https://images.zenhubusercontent.com/62796e60fbcb60d8858283eb/5940f4da-f0e6-4de4-a18e-5e2d104c6205)

![image.png](https://images.zenhubusercontent.com/62796e60fbcb60d8858283eb/a190da62-aa43-439d-8e2f-e7b3ed034051)

applied manifest
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.37.0
    control-plane: controller
  name: source-controller-v32
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source-controller-v32
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: source-controller-v32
    spec:
      containers:
        - args:
            - --events-addr=http://notification-controller.flux-system.svc.cluster.local./
            - --watch-all-namespaces=true
            - --log-level=info
            - --log-encoding=json
            - --storage-path=/data
            - --storage-adv-addr=source-controller-v32.$(RUNTIME_NAMESPACE).svc.cluster.local.
          env:
            - name: RUNTIME_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ghcr.io/fluxcd/source-controller:v0.32.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          name: manager
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
            - containerPort: 8080
              name: http-prom
              protocol: TCP
            - containerPort: 9440
              name: healthz
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /tmp
              name: tmp
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 1337
      serviceAccountName: source-controller
      terminationGracePeriodSeconds: 10
      volumes:
        - emptyDir: {}
          name: data
        - emptyDir: {}
          name: tmp
```
