### ISSUE TITLE
Getting {"uri": "/oauth2/userinfo", "status": 400}  with dex integration

### ISSUE THREAD

**Issue by mukulgit123** [weaveworks/weave-gitops#2955]
**Describe the bug**

We are extensively using fluxcd in our environments and recently we started to plan for the deployment of weave-works gitops dashboard for visualisation.

We are already using community dex integrated with Azure AD which works absolutely fine for all our needs from Grafana, ArgoCD, Kiali etc. While we are doing the similar integration with ww-gitops we are able to see in dex logs that login happens successfully post installation. However, after login the browser returns to the login page and even after setting logLevel as debug we just get to see logs as below for ww-gitops pod deployed in our environment. 

```
│ 2022-11-01T10:34:04.432Z    DEBUG    gitops    middleware/middleware.go:57    request success    {"uri": "/oauth2?return_url=https%3A%2F%2Fww-gitops.${OUR_DOMAIN}", "status": 303}                                                    │
│ 2022-11-01T10:34:13.765Z    DEBUG    gitops    middleware/middleware.go:57    request success    {"uri": "/oauth2/callback?code=******** │
│ 2022-11-01T10:34:13.842Z    DEBUG    gitops    middleware/middleware.go:57    request success    {"uri": "/", "status": 200}                                                                                                                      │
│ 2022-11-01T10:34:13.842Z    DEBUG    gitops    middleware/middleware.go:57    request success    {"uri": "/", "status": 200}                                                                                                                      │
│ 2022-11-01T10:34:14.045Z    DEBUG    gitops    middleware/middleware.go:57    request success    {"uri": "/", "status": 200}                                                                                                                      │
│ 2022-11-01T10:34:14.413Z    DEBUG    gitops    middleware/middleware.go:57    request success    {"uri": "/v1/featureflags?", "status": 200}                                                                                                      │
│ 2022-11-01T10:34:14.414Z    INFO    gitops    middleware/middleware.go:61    request error    {"uri": "/oauth2/userinfo", "status": 400}                                                                                                          │
│ 2022-11-01T10:34:14.600Z    INFO    gitops    middleware/middleware.go:61    request error    {"uri": "/oauth2/userinfo", "status": 400}                                                                                                          │
│ 2022-11-01T10:34:23.842Z    DEBUG    gitops    middleware/middleware.go:57    request success    {"uri": "/", "status": 200} 
```

**Environment**

- Weave-Gitops Version - 0.10.1
- Flux Version - 0.25.3
- Kubernetes version - 1.22

**To Reproduce**

1. Install ww-gitops dashboard using below HelmRelease resource on your cluster after replacing the respective variables in below manifest. 

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: cluster-core
spec:
  chart:
    spec:
      chart: weave-gitops
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
        namespace: cluster-core
      version: 4.0.6
  install:
    remediation:
      retries: -1
    timeout: 10m0s
  interval: 10m
  targetNamespace: cluster-core
  upgrade:
    timeout: 10m1s
  values:
    adminUser:
      create: true
      passwordHash: ${OUR_PASSWORD_HASH}
      username: admin
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: ww-gitops
            topologyKey: kubernetes.io/hostname
          weight: 100
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: ww-gitops
            topologyKey: topology.kubernetes.io/zone
          weight: 100
    ingress:
      annotations:
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-buffer-size: 24k
        nginx.ingress.kubernetes.io/proxy-buffers-number: "32"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      enabled: true
      hosts:
      - host: ww-gitops.${OUR_DOMAIN}
        paths:
        - path: /
          pathType: ImplementationSpecific
      ingressClassName: ${OUR_NGINX_INGRESS_CLASS}
      tls:
      - hosts:
        - ww-gitops.${OUR_DOMAIN}
        secretName: ww-${OUR_TLS_SECRET}-tls
    logLevel: debug
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: ${DEFAULT_PORT}
          prometheus.io/scrape: "true"
        port: 2112
    oidcSecret:
      clientID: ${OUR_DEX_CLIENT_ID}
      clientSecret: ${OUR_DEX_CLIENT_SECRET}
      create: true
      issuerURL: https://dex.${OUR_DOMAIN}
      redirectURL: https://ww-gitops.${OUR_DOMAIN}/oauth2/callback
    rbac:
      impersonationResourceNames:
      - admin
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    tolerations:
    - operator: Exists
```
2. Setup the callback URLs in the dex configuration for successful registration. 
```
│     redirectURIs:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             │
│     - https://ww-gitops.${OUR_DOMAIN}/oauth2/callback                                                                                                                                                                                                                                                                                 │
│     - https://ww-gitops.${OUR_DOMAIN}                                                                                                                                                                  │
│     - http://localhost:8250/oidc/callback                                                                                                                                                                          │                                                                                                                                                   │                                                                                                                                          
│     - https://localhost:9001/oauth2/callback                                                                                                                                                                       │
│     - https://0.0.0.0:9001/oauth2/callback                                                                                                                                                                         │
│     - http://0.0.0.0:9001/oauth2/callback                                                                                                                                                                          │
│     - http://localhost:4567/oauth2/callback                                                                                                                                                                        │
│     - https://localhost:4567/oauth2/callback                                                                                                                                                                       │
│     - http://localhost:3000/oauth2/callback                                                                                                                                                                        │
│     - http://ww-gitops.${OUR_DOMAIN}/oauth2/callback                                                                                                                                                    │
│     - http://ww-gitops.${OUR_DOMAIN}                                                                                                                                                             
```
3. Try logging on to ww-gitops dashboard using "Login with OIDC Provider."

**Expected behavior**

We expected login to happen successfully using OIDC. 

**Actual Behavior**

Dex is able to return successful login as we can see in the logs but we are redirected to the login page with 400 error for /oauth2/userinfo

Note: Login works fine with the admin user that we are creating.
