### ISSUE TITLE
Investigate status for daemonsets

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#2967]
Whilst attempting to reproduce permissions issue, noticed we didn't have a status on daemonsets, at least given the example here https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/. 

<img width="1401" alt="Screenshot 2022-11-03 at 11 50 43" src="https://user-images.githubusercontent.com/19860021/199713498-13d5eaad-fe86-479f-a38b-8d2e892d20a4.png">

The status from the yaml output showed:
```
status:  currentNumberScheduled: 1  desiredNumberScheduled: 1  numberAvailable: 1  numberMisscheduled: 0  numberReady: 1  observedGeneration: 1  updatedNumberScheduled: 1
```

compared to a deployment:

```
status:  availableReplicas: 2  conditions:    - lastTransitionTime: 2022-11-01T20:51:38Z      lastUpdateTime: 2022-11-01T20:51:38Z      message: Deployment has minimum availability.      reason: MinimumReplicasAvailable      status: "True"      type: Available    - lastTransitionTime: 2022-11-01T20:51:09Z      lastUpdateTime: 2022-11-01T20:51:38Z      message: ReplicaSet "podinfo-5787749dfc" has successfully progressed.      reason: NewReplicaSetAvailable      status: "True"      type: Progressing  observedGeneration: 2  readyReplicas: 2  replicas: 2  updatedReplicas: 2
```

I believe our status comes from `status.conditions` which wasn't there on the daemonset.

Wondering if we can display anything meaningful for users in this scenario.

**Comment by jpellizzari** [comment]
We use `status.conditions` to compute the state of the object, which works for many objects, but `DaemonSet` status looks like this:

```
status:  
  currentNumberScheduled: 1  
  desiredNumberScheduled: 1  
  numberMisscheduled: 0  
  numberReady: 0  
  numberUnavailable: 1  
  observedGeneration: 1  
  updatedNumberScheduled: 1
```
