### ISSUE TITLE
error getting flux version 

### ISSUE THREAD

**Issue by gabrielfsousa** [weaveworks/weave-gitops#3004]
**ERROR:**
error getting flux version    {"error": "error getting list of objects"}

**Environment**

- Weave-Gitops Version: v0.10.2
- Flux Version: v0.36.0
- Kubernetes version: v1.23.5

**Comment by chanwit** [comment]
Thank you for reporting this @gabrielfsousa 
We'll take a look at it shortly

**Comment by gabrielfsousa** [comment]
i just installed flux.
Made a deployment of metrics-server using flux, worked with success 

`
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 1m
  url: https://github.com/kubernetes-sigs/metrics-server
  ref:
    branch: master
  ignore: |-
    /*
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/metrics-server
      version: "3.8.2"
      sourceRef:
        kind: GitRepository
        name: metrics-server
        namespace: kube-system
  values:
    replicas: 1
    defaultArgs:
      - --cert-dir=/tmp
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
      - --kubelet-insecure-tls
`

then installed weave UI

`
gitops create dashboard ww-gitops \
  --password=$PASSWORD \
  --export > ./clusters/my-cluster/weave-gitops-dashboard.yaml
`

pod is running UI is working, but empty.
and i have "error getting flux version {"error": "error getting list of objects"}" in the container log

**Comment by ozamosi** [comment]
Looking at your HelmRelease object, I would expect to see something like
```yaml
    adminUser:
      create: true
      passwordHash: some gobbledygook
      username: admin
```
inside the values key, if `$PASSWORD` was set to a non-empty value when you ran it. If those where there, then the helm chart would automatically create a clusterrolebinding between your local admin user and appropriate roles for the resources you need.

If you've created the login secret yourself or are using OIDC, then you need to set up user permissions separately - there's more information in our manual here: https://docs.gitops.weave.works/docs/configuration/recommended-rbac-configuration/

Did you ever have the `adminUser` stanza?

**Comment by makkes** [comment]
@gabrielfsousa checking in to see whether you had the chance to look at @ozamosi's comment above.

**Comment by loganmarchione** [comment]
@makkes @ozamosi I'm also getting the error

```
2022-12-27T23:07:56.907Z        ERROR   gitops.core-server      server/version.go:105   error getting flux version      {"error": "error getting list of objects"}
```

Below is my HelmRelease config for weave-gitops.

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weaveworks
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.10
      sourceRef:
        kind: HelmRepository
        name: weave-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # https://docs.gitops.weave.works/docs/references/helm-reference/
  values:
    image:
      repository: ghcr.io/weaveworks/wego-app
    ingress:
      enabled: false
    service:
      create: true
      type: ClusterIP
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    adminUser:
      create: true
    rbac:
      create: true
      impersonationResources: ["users"]
      impersonationResourceNames:
        - admin
```

I've created a secret like below. I can login to the web UI with `admin` and the password, but the UI says `No data`.

```
kubectl create secret generic cluster-user-auth \
  --namespace flux-system \
  --from-literal=username=admin \
  --from-literal=password='bcrypt_password_hash_goes_here'
```

**Comment by makkes** [comment]
@loganmarchione the HelmRelease manifest you pasted above doesn't even install the Weave GitOps Dashboard:
```
Helm install failed: execution error at (weave-gitops/templates/admin-user-creds.yaml:13:31): passwordHash must be set!
```

**Comment by loganmarchione** [comment]
@makkes thanks for the reply, I figured it out! FWIW, I'm no longer receiving `error getting flux version`

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.10
      sourceRef:
        kind: HelmRepository
        name: weave-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # https://docs.gitops.weave.works/docs/references/helm-reference/
  values:
    image:
      repository: ghcr.io/weaveworks/wego-app
    ingress:
      enabled: false
    service:
      create: true
      type: ClusterIP
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    adminUser:
      create: true
      createClusterRole: true
      createSecret: false
      username: "admin"
    rbac:
      create: true
      impersonationResources: ["users", "groups"]
```
