### ISSUE TITLE
AKS clusters with Microsoft.Flux not detected as Flux

### ISSUE THREAD

**Issue by kingdonb** [weaveworks/weave-gitops#3049]
**Describe the bug**

When `gitops beta run ./test-path --no-session` is run against a cluster that has AKS' flux installed (eg. https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2) the environment is not detected as Flux, and a potentially destructive overwrite of the controllers is apparently undertaken with whatever `flux` CLI is in the user's path.

(No prompt precedes this action.)

![Screenshot 2022-11-22 at 1 22 42 PM](https://user-images.githubusercontent.com/3286998/203578101-09c0eb6e-c969-4ff9-8987-9d3817412a8d.png)

**Environment**

- Weave-Gitops Version
$ gitops version
Current Version: 0.10.2
GitCommit: 56d11cb9a8d14670eec713e9e3fe105da0e18476
BuildTime: 2022-11-10T15:22:34Z
Branch: releases/v0.10.2
- Flux Version - 0.36.0
- Kubernetes version - Azure AKS (the default cluster version, I think right now is 1.21.x - the infra code is here but I don't think it's important: https://github.com/kingdonb/learn-terraform-provision-aks-cluster/blob/main/aks-cluster-1.tf)

**To Reproduce**

Just as in the screenshot above

**Expected behavior**

It should detect the Flux controllers that are from Microsoft.Flux and utilize them instead of overwriting them.
(Generally, I think that failure mode is bad – if the labels did not detect any resources, but the dry-run apply changes some resources, then I think Weave GitOps should not proceed with the install operation, not overwrite anything, it should balk and quit.)

**Actual Behavior**

In the screenshot

**Additional Context (screenshots, logs, etc)**

**Comment by makkes** [comment]
Thanks for reporting this @kingdon. Would you mind please paste the output of the following command?

```kubectl get ns -l app.kubernetes.io/part-of=flux --show-labels```

This is basically what the `gitops beta run` command does when checking if Flux is installed and it looks like this query doesn't return anything so I suppose that MS is changing the labels of the Flux Namespace in some way.

**Comment by kingdonb** [comment]
There was no output, it looks like the flux-system namespace doesn't get labeled.

FYI:
```
$ helm ls -A --all
NAME	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION
flux	flux-system	1       	2022-11-23 18:53:29.959835553 +0000 UTC	deployed	azure-k8s-flux-1.6.1	1.6.1
```

This is the Helm chart that deploys Flux from AKS's extension above. Below, the deployments in `flux-system` get some labels.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: flux
    meta.helm.sh/release-namespace: flux-system
  creationTimestamp: "2022-11-23T18:53:37Z"
  generation: 1
  labels:
    app.kubernetes.io/component: kustomize-controller
    app.kubernetes.io/instance: flux
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: microsoft.flux
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.35.0
    clusterconfig.azure.com/extension-version: 1.6.1
    control-plane: controller
```

But the namespace itself does not:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-11-23T18:53:27Z"
  labels:
    kubernetes.io/metadata.name: flux-system
  name: flux-system
  resourceVersion: "3160"
  uid: 298a4fe4-3a17-468f-b94d-fbd04fbca922
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```
