### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by AntonChernyaevArammeem** [weaveworks/weave-gitops#3255]
failed to install 

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  annotations:
    metadata.weave.works/description: This is the source location for the Weave GitOps Dashboard's helm chart.
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides a simple way to get insights into your GitOps workloads.
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      version: v0.14.1
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1h0m0s
  values:
    adminUser:
      create: true
      passwordHash: $2a$10$Mr9Upim6cN5sv3HLu49LCuXcQN1e/Lyk4gD/JPzUmjAorCwJP9Uxi
      username: admin
```
error on source controller

`{"level":"error","ts":"2023-01-10T14:31:17.423Z","msg":"Reconciler error","controller":"helmchart","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"HelmChart","HelmChart":{"name":"flux-system-ww-gitops","namespace":"flux-system"},"namespace":"flux-system","name":"flux-system-ww-gitops","reconcileID":"a6cbba95-7b02-47f3-bc90-08e26baa3449","error":"chart pull error: failed to download chart for remote reference: failed to copy: httpReadSeeker: failed open: failed to do request: Get \"https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:28e89ffe70d393722c1a8004fafe6793649647304e3cb0839d5684fd7a357cb7?se=2023-01-10T14%3A40%3A00Z&sig=GnxigfHs%2F9wjMkshUADhERuRwfPG96L3CXkFLNxjp1g%3D&sp=r&spr=https&sr=b&sv=2019-12-12\": net/http: TLS handshake timeout"}`

**Environment**

- Weave-Gitops Version 0.14.1
- Flux Version v0.37.0
- Kubernetes version v1.22.15-eks-fb459a0

**To Reproduce**
just try apply these two manifests (generated through gitops)
