### ISSUE TITLE
Image Policy details fail to show when Policy name is different from Repository name

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops#3356]
**Describe the bug**
Currently, if the Policy object is named differently from the Repository object, the Policy details fail to show (normally shown below the Repository details). The UI should not rely on names for associating objects, a user may have an image repository named `foo` and an image policy named `bar` that references `foo`.

**Environment**

- Weave-Gitops Version 0.16.0
- Flux Version 0.38
- Kubernetes version (any supported by Flux)

**To Reproduce**

1. Add the following manifests to your repo
   ```
   apiVersion: image.toolkit.fluxcd.io/v1beta1
   kind: ImageRepository
   metadata:
     name: podinfo-repo
     namespace: default
   spec:
     image: ghcr.io/stefanprodan/podinfo
     interval: 1h
   ---
   apiVersion: image.toolkit.fluxcd.io/v1beta1
   kind: ImagePolicy
   metadata:
     name: podinfo-policy
     namespace: default
   spec:
     imageRepositoryRef:
       name: podinfo-repo
     policy:
       semver:
         range: 5.0.x
   ```
2. Go to `IMAGE AUTOMATION` section and click on the `IMAGE REPOSITORIES` tab
3. Click on the link to the `podinfo-repo` Image Repository

**Expected behavior**

Ideally the details of the Policy object that references the Repository selected are shown. If this is not performant, then perhaps we should add a new tab for Policies, show a list of Policies there and show the Repository object details along with the Policy object details.

**Actual Behavior**
An error shown indicating no Policy exists with that name.

**Additional Context (screenshots, logs, etc)**
