### ISSUE TITLE
Improve output of "wego app add"

### ISSUE THREAD

**Issue by pzfreo** [weaveworks/weave-gitops#346]
**Describe the bug**
The output of `wego app add` is very confusing (and also has some incorrect output as well "./wego" instead of ".wego/"
It should print high-level steps and useful info (e.g. the repo, branch, path, app name, etc). The current output could be part of "verbose" mode.

There is also a spelling mistake "commiting" instead of "committing".

**To Reproduce**
```
wego app add .

Updating parameters from environment... using URL: 'ssh://git@github.com/pzfreo/podinfo-deploy.git' of origin from git config...

done

Checking cluster status... FluxInstalled

Uploading deploy key
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo-deploy
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: podinfo-deploy
  url: ssh://git@github.com/pzfreo/podinfo-deploy.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kind-kind-podinfo-deploy
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./wego/targets/kind-kind
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo-deploy
  validation: client

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo-deploy
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./wego/apps/podinfo-deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo-deploy
  validation: client

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo-deploy
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo-deploy
  validation: client

Commiting and pushing wego resources for application...
App manifests are up to date
```

I would expect the output to be more like:

```
Adding application
name: podinfo-deploy
git repo: ssh://git@github.com/pzfreo/podinfo-deploy.git
branch: main
path: .
type: kustomize
* validating flux installed ✔
* checking for existing deploy key ✖
* creating deploy key ✔
* adding deploy key to repository ✔
* creating GitOps Automation ✔
* create PR ✔
 
To continue please review and merge the pull request:
https://github.com/pzfreo/podinfo-deploy/pull/1 
```
