### ISSUE TITLE
UI - uses only one group for impersonation

### ISSUE THREAD

**Issue by camaeel** [weaveworks/weave-gitops#3485]
**Describe the bug**

I set up Auth0 as my OIDC provider. In the oidc-auth secret I set up: `claimGroups = "https://custom.domain.eu/roles"`. 
I created kubernetes RBAC ClusterRoles and ClusterRoleBindings for flux-admin and flux-readonly.
I also set in the helm chart values:
```
       rbac:
        impersonationResourceNames: 
        - flux-admin
        - flux-readonly
        impersonationResources: 
        - groups
        - users
```
When I login and try to view applications tab I see in the logs: 
```
flux-dashboard-weave-gitops-74f78f9c76-gdp95 weave-gitops 2023-03-06T20:34:44.400Z	ERROR	gitops	clustersmngr/factory.go:566	failed filtering namespaces	{"cluster": "Default", "user": "xxxx@gmail.com", "error": "user namespace access: groups \"vault-apps-admin\" is forbidden: User \"system:serviceaccount:flux-system:flux-dashboard-weave-gitops\" cannot impersonate resource \"groups\" in API group \"\" at the cluster scope"}
```

When I removed from the user all the other groups except flux-admin in Auth0, then re-logged I got access properly. So it looks like in case of more than one group on the user only one (first?) is checked.

**Environment**

- Weave-Gitops Version: 0.18.0
- Flux Version
    flux: v0.40.2
    helm-controller: v0.30.0
    kustomize-controller: v0.34.0
    notification-controller: v0.32.1
    source-controller: v0.35.2
- Kubernetes version: v1.25.6+k3s1

**To Reproduce**
1. Install recent flux
2. Install recent gitops (dashboard for flux)
3. Configure oidc secret and set up oidc group claims.
4. Create a user that has more groups than one. If you are unlucky then dashboard takes for impersonation wrong group.

**Expected behavior**

Should have access to applications even if logged in user has more than one group returned in JWT.

**Actual Behavior**

Only one (first?) group is used for checking impersonation access. 

**Additional Context (screenshots, logs, etc)**

**Comment by camaeel** [comment]
It works fine when I remove all the groups from my OIDC except the one that is needed. So it is not the issue with `kubectl auth can-i `, rather it checks only one group from the token.

**Comment by bigkevmcd** [comment]
This sounds more like a Kubernetes RBAC configuration issue, I'm not quite sure what we can do here?

**Comment by foot** [comment]
@camaeel curious if you found anything here?

You can see the groups we've found by clicking on your user-id in the profile menu.

<img width="248" alt="image" src="https://user-images.githubusercontent.com/22008/224961411-5e41cc67-e975-48ff-8fc4-6e97e08068b0.png">

Do we show all the groups there?

**Comment by camaeel** [comment]
Yes, all the groups where there.

**Comment by foot** [comment]
The error message provided is interesting..

> `flux-dashboard-weave-gitops-74f78f9c76-gdp95 weave-gitops 2023-03-06T20:34:44.400Z	ERROR	gitops	clustersmngr/factory.go:566	failed filtering namespaces	{"cluster": "Default", "user": "xxxx@gmail.com", "error": "user namespace access: groups \"vault-apps-admin\" is forbidden: User \"system:serviceaccount:flux-system:flux-dashboard-weave-gitops\" cannot impersonate resource \"groups\" in API group \"\" at the cluster scope"}`

If you remove the `impersonationResourceNames` so it goes back to the default of `[]` does that help at all?

**Comment by seb-inf** [comment]
I have the same issue with OIDC on Dex and Google. Gitops panel iterates first username and rest of groups which can't impersonate due `impersonationResourceNames`. 

Can I limit somehow panel to only use desired groups?

**Comment by foot** [comment]
> Can I limit somehow panel to only use desired groups?

Not right now unfortunately. 

If I understand it correctly, adding all OIDC groups to the list of `impersonationResourceNames` would fix this? But that might not be an acceptable workaround?

Given that not all the RBAC for the weave-gitops-server might be specified in the helm-chart, its hard to accurately determine the groups we can impersonate like this dynamically. 🤔

**Comment by bigkevmcd** [comment]
@seb-inf Does this work with `kubectl auth can-i --as-user <user> --as-group <group1> --as-group <group2> get namespaces` ?

i.e. if you provide the same set of groups to kubectl auth does it succeed?

**Comment by bigkevmcd** [comment]
> What user should I use for kubectl/impersonation?
The auth mechanism verifies the incoming JWT ID token, and impersonates the `email` and `groups` (you can configure both of these tho').

So, `--as <whatever user you need to test it with`.

One option we could try is allowing you to filter the group that we impersonate, restricting it to a specific set.

For example, we already have a Secret with various OIDC config items, we could add...

```
data:
  allowedImpersonationGroupNames: my-group1,my-group2,test-group
```

When we're setting up the impersonation, we **could** remove groups that are not in that set from the impersonation groups list.

**Comment by seb-inf** [comment]
Oky, so we use GKE with Google Groups for RBAC

We have groups like:

* gke-developers-team-foo@
* gke-developers-team-bar@
* gke-devops-team@

And now `gke-devops-team` have all permissions from Google IAM. Groups `gke-developers-team-foo@` and `gke-developers-team-bar@`  have access to list all namespaces from Google IAM and k8s RBAC access to specific namespaces like: 

* gke-developers-team-foo@
  * service-foo-a
  * service-foo-b
  * service-foo-c
* gke-developers-team-bar@
  * service-bar-a
  * service-bar-b
  * service-bar-c

And users in these groups can use kubectl etc

Now, with default settings:

```yaml
 impersonationResourceNames: []
 # -- Limit the type of principal that can be impersonated
 impersonationResources: ["users", "groups"]
```

All works fine, user in team foo has access to only foo namespaces, when user is in both groups has access to both.

The problem is with this config:

```yaml
 impersonationResourceNames:
 - gke-developers-team-foo@
 - gke-developers-team-bar@
 - gke-devops-team@
 # -- Limit the type of principal that can be impersonated
 impersonationResources: ["users", "groups"]
```

User added to `gke-developers-team-foo@` and other group `gke-developers-team-baz@` and then gitops ends with error:

```
2023-04-05T09:52:38.830Z    ERROR    gitops    clustersmngr/factory.go:566    failed filtering namespaces    {"cluster": "Default", "user": "developer1.test@corp", "error": "user namespace access: users \"developer1.test@corp\" is forbidden: User \"system:serviceaccount:weave-gitops:weave-gitops\" cannot impersonate resource \"users\" in API group \"\" at the cluster scope"}
```

```
kubectl get deployments --as-group gke-developers-team-foo@ --as developer1.test@corp -n service-foo-a
NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
foo-api      1/1     1            1           130d
foo-worker   1/1     1            1           130d
```

And I can use whatever I want as user.

```
kubectl get deployments --as-group gke-developers-team-foo@ --as whatever -n service-foo-a
NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
foo-api      1/1     1            1           130d
foo-worker   1/1     1            1           130d
```

Foo user doesn't have access to bar services

```
kubectl get deployments --as-group gke-developers-team-foo@ --as whatever -n service-bar-a
Error from server (Forbidden): deployments.apps is forbidden: User "whatever" cannot list resource "deployments" in API group "apps" in the namespace "service-bar-a"
```

> Does this work with kubectl auth can-i --as-user <user> --as-group <group1> --as-group <group2> get namespaces ?
> i.e. if you provide the same set of groups to kubectl auth does it succeed?

```
kubectl auth can-i --as whatever --as-group gke-developers-team-foo@ get namespaces
Warning: resource 'namespaces' is not namespace scoped

no
```

```
kubectl auth can-i --as whatever --as-group gke-developers-team-foo@ get pods -n service-foo-a
yes
```

```
kubectl auth can-i --as whatever --as-group gke-developers-team-foo@ --as-group gke-developers-team-bar@ get namespaces
Warning: resource 'namespaces' is not namespace scoped

no
```

**Comment by Just-Insane** [comment]
I appear to be facing the same error with my user in Authentic (idP) having multiple groups returned. using `kubectl auth can-i` with the same multiple groups (in any order) succeeds, however, the dashboard fails with an error like:

```
failed creating user client to pool: failed creating client for cluster=Default: could not create RESTMapper from config: unknown
```

Though when I click on my user in the top right, it says I'm not part of any groups?

**Comment by Jimmy-Newtron** [comment]
From the kubernetes impersonation doc https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation

I would suggest to split the User and Group impersonation into separate rules into the ClusterRole flux-dashboard-weave-gitops

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: limited-impersonator
rules:
# Can impersonate the user "jane.doe@example.com"
- apiGroups: [""]
  resources: ["users"]
  verbs: ["impersonate"]
  resourceNames: ["jane.doe@example.com"]

# Can impersonate the groups "developers" and "admins"
- apiGroups: [""]
  resources: ["groups"]
  verbs: ["impersonate"]
  resourceNames: ["developers","admins"]

# Can impersonate the extras field "scopes" with the values "view" and "development"
- apiGroups: ["authentication.k8s.io"]
  resources: ["userextras/scopes"]
  verbs: ["impersonate"]
  resourceNames: ["view", "development"]

# Can impersonate the uid "06f6ce97-e2c5-4ab8-7ba5-7654dd08d52b"
- apiGroups: ["authentication.k8s.io"]
  resources: ["uids"]
  verbs: ["impersonate"]
  resourceNames: ["06f6ce97-e2c5-4ab8-7ba5-7654dd08d52b"]
  ```
