### ISSUE TITLE
Cannot Turn User Auth off on Sign In Page

### ISSUE THREAD

**Issue by scott-kausler** [weaveworks/weave-gitops#3499]
**Describe the bug**

**Environment**
Kubernetes/OpenShift

- Weave-Gitops Version
0.18.0

- Flux Version
0.36.0

- Kubernetes version
1.24

**To Reproduce**
Set the following in the gitops-server helm chart and deploy
```
    envVars:
      - name: WEAVE_GITOPS_FEATURE_CLUSTER_USER_AUTH
        value: "false"
      - name: CLUSTER_USER_AUTH
        value: "false"
```

**Expected behavior**

The basic auth Username/Password fields do not appear on the sign in page.

**Actual Behavior**

The basic auth Username/Password fields DO appear on the sign in page.
