### ISSUE TITLE
Version 0.21.1 CrashLoop

### ISSUE THREAD

**Issue by selfsk** [weaveworks/weave-gitops#3616]
**Describe the bug**

New version (0.21.1) of `weave-gitops` could not start and failing with error:

```
Error: could not initialise authentication server: could not create auth server: could not get secret for cluster user, resource name may not be empty
```

**Environment**

- Weave-Gitops Version - 0.21.1
- Flux Version - 0.31.1
- Kubernetes version - 1.22 (AWS EKS)

**To Reproduce**

Use this helm chart and let flux update chart automatically to latest version, which brings 0.21.1

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: www-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: www-gitops
  interval: 1h0m0s
  values:
    rbac:
      create: true
      impersonationResources: ["users"]
    adminUser:
      create: true
      createSecret: false
      username: "gitops-user"
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: www-gitops
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/weaveworks/charts
```

**Expected behavior**

New version of chart successfully deployed

**Actual Behavior**

After new version of chart deployed, new version is failing with `CrashLoopBackoff`

**Additional Context (screenshots, logs, etc)**

**Comment by selfsk** [comment]
I think it's not a bug technically, but mostly configuration problem. Old helm chart had:
```
viewSecretsResourceNames: ["cluster-user-auth", "oidc-auth"]
```

New one have only `oidc-auth`, so it breaks weave-gitops if no oidc-auth configured. To make it work, just updated flux kustomization:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: www-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: www-gitops
  interval: 1h0m0s
  values:
    rbac:
      create: true
      impersonationResources: ["users"]
      viewSecretsResourceNames: ["cluster-user-auth"]
    adminUser:
      create: true
      createSecret: false
      username: "gitops-user"
```
