### ISSUE TITLE
Base url setting for gitops dashboard

### ISSUE THREAD

**Issue by wicharypawel** [weaveworks/weave-gitops#3628]
Hello 👋🏻 
recently I was unsuccessful trying to configure and run weave-gitops dashboard for subpath. It would be nice to have a support for base url (aka prefix) configuration.

**Problem**
Weave gitops does not support base url/prefix configuration.

![image](https://user-images.githubusercontent.com/11590420/232435906-6f607e36-6fde-4688-a298-423369bcc469.png)

*Note path to asset file does not contain base url/prefix.*

**Solution**

It would be possible to host weave application at subpath.

```
https://application.com <- application url
https://application.com/internal/gitops/ <- gitops dashboard
https://application.com/internal/gitops/index.html <- gitops dashboard index.html
https://application.com/internal/gitops/index.780a4a15.css <- gitops dashboard asset file
https://application.com/internal/gitops/index.4417e847.js <- gitops dashboard asset file
```

Following ingress configuration would redirect to fully functional application.
```
      - path: /internal/gitops/(.*)
        pathType: Prefix
        backend:
          service:
            name: ww-gitops-weave-gitops
            port:
              number: 9001
```

I would assume that such configuration is defined as a part of a helm release. Suggested property name pathPrefix.

Any help would be greatly appreciated.
