### ISSUE TITLE
Improve getting Flux version in the version endpoint

### ISSUE THREAD

**Issue by opudrovs** [weaveworks/weave-gitops#3666]
Reported by @Nalum 

> The Flux version in the footer of Weave GitOps OSS Dashboard, should that reflect the version installed or is it something else?

![version_1](https://user-images.githubusercontent.com/8824708/236011590-5400e3c9-6524-497c-b94f-60f1d4a0918e.png)

> I'm running v0.41.2 in this cluster

> Which the runtime page picks up

![version_2](https://user-images.githubusercontent.com/8824708/236011601-15126022-c4e9-41e4-8760-87ed03b446a5.png)

Solution:

The Flux version returned by the `version` endpoint is the value of the label "app.kubernetes.io/version" in the first object with labels `"[app.kubernetes.io/part-of](http://app.kubernetes.io/part-of)": "flux"` for which the version label is set. The list of objects looped through is not limited to only deployments or pods. The version endpoint must be picking the version from some of the leftover older Flux objects.

So, we can switch to using the version on the first deployment or pod which is a part of Flux. This should make the endpoint return the actual version of installed Flux.

**Comment by makkes** [comment]
Possibly related to #3665

**Comment by Nalum** [comment]
I found where `v0.26.3` is coming from, the setup of the cluster is done with Terraform which also sets up the namespaces in the cluster, which looks like this:

```yaml
  flux-system:
    labels:
      app.kubernetes.io/instance: flux-system
      app.kubernetes.io/part-of: flux
      app.kubernetes.io/version: v0.26.3
      pod-security.kubernetes.io/warn: restricted
      pod-security.kubernetes.io/warn-version: latest
      prometheus: monitorme
    annotations:
      name: flux-system
```

I'll update this and the scripts that update Flux in this system so that it doesn't fall behind again.
