### ISSUE TITLE
Image Automations not displayed in UI

### ISSUE THREAD

**Issue by kfalconer** [weaveworks/weave-gitops#3824]
**Describe the bug**

When using the FluxCD Image automation feature, there are no resources displayed in the UI

**Environment**

- Weave-Gitops Version: 0.27.0
- Flux Version: 2.0.0-rc5
- Kubernetes version: 1.25.10

**To Reproduce**
Using the following Image Automation yamls.
````yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  image: ghcr.io/stefanprodan/podinfo
  interval: 1h
  secretRef:
    name: docker-cfg
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: podinfo
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    semver:
      range: 0.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: podinfo-automation
  namespace: podinfo
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: test-pr
  update:
    path: ./cluster/staging
    strategy: Setters
````

**Expected behavior**

List of image automation resources

**Actual Behavior**

No resources are displayed
