### ISSUE TITLE
No padding on Suspend button in Source Detail

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#4001]
<img width="292" alt="image" src="https://github.com/weaveworks/weave-gitops/assets/65822698/4b7b9fa1-1d67-4056-a0c2-47d0d9e07855">

I can only see it on detail pages for Helm Charts for some reason

**Comment by opudrovs** [comment]
@joshri I don't see any issues with Suspend button padding in the latest OSS main or in OSS or enterprise (demo 3) staging:

<img width="1526" alt="Screenshot 2023-09-15 at 18 06 29" src="https://github.com/weaveworks/weave-gitops/assets/8824708/dae66635-0c4a-482c-af72-c7896446f512">

<img width="1504" alt="Screenshot 2023-09-15 at 18 06 36" src="https://github.com/weaveworks/weave-gitops/assets/8824708/03fff91f-f5e1-4810-a737-22e316a53253">

<img width="1530" alt="Screenshot 2023-09-15 at 18 06 55" src="https://github.com/weaveworks/weave-gitops/assets/8824708/0078ed47-67dd-4b1b-a591-595fe9612dbc">

Are you running OSS in Tilt or via `yarn start`?

Could you please re-check the issue?

**Comment by opudrovs** [comment]
Tried it with `yarn start`, the padding looks fine to me:

<img width="1522" alt="Screenshot 2023-09-15 at 18 43 46" src="https://github.com/weaveworks/weave-gitops/assets/8824708/3dc38c83-e253-4488-82d7-73d543ce300e">

<img width="1527" alt="Screenshot 2023-09-15 at 18 43 53" src="https://github.com/weaveworks/weave-gitops/assets/8824708/cb07dca3-a23a-4678-898a-96b0d865b8c7">

**Comment by joshri** [comment]
@opudrovs - have you checked it out on a Helm Chart? I could only see this on Helm Charts for some odd reason

**Comment by opudrovs** [comment]
OK, thanks. Checked HelmChart detail pages locally with Tilt and in staging: I can see that the button looks a bit different indeed and for HelmCharts only. Its padding stays the same, but its width is reduced:  54+ for me instead of 61+. Crazy.

What is weird, I can only see this issue locally
<img width="1531" alt="Screenshot 2023-09-15 at 20 06 30" src="https://github.com/weaveworks/weave-gitops/assets/8824708/ab28bf68-bdbc-4476-aa61-ebd9d1bc83d8">

<img width="1528" alt="Screenshot 2023-09-15 at 20 08 29" src="https://github.com/weaveworks/weave-gitops/assets/8824708/b0906802-0fa0-451a-b3d7-9ccf5cfef4a6">

not in staging:

<img width="1531" alt="Screenshot 2023-09-15 at 20 06 41" src="https://github.com/weaveworks/weave-gitops/assets/8824708/84dc123c-11dd-4823-8a86-eb796b14da2f">

**Comment by opudrovs** [comment]
Also see an error I have not seen before with cluster name = Default and cluster not found message. My cluster name is wego-dev and its liveness check is passing fine in Tilt:

<img width="1146" alt="Screenshot 2023-09-15 at 20 15 50" src="https://github.com/weaveworks/weave-gitops/assets/8824708/d28aa192-4b38-4c48-9f80-abcbd15df858">

**Comment by opudrovs** [comment]
Have you seen anything like that before?

**Comment by opudrovs** [comment]
Besides, there is an issue (more prominent on shorter HelmChart suspend button) with the rotating indicator going beyond the Suspend button boundaries:

https://github.com/weaveworks/weave-gitops/assets/8824708/e281c6e6-6e3b-49bb-9cbe-d0b9710fe880

So, if both of these problems are new, I will create issues for them on Monday.

**Comment by joshri** [comment]
> Also see an error I have not seen before with cluster name = Default (in the address bar) and cluster not found message. My cluster name is wego-dev and its liveness check is passing fine in Tilt:
> 
> <img alt="Screenshot 2023-09-15 at 20 15 50" width="1146" src="https://user-images.githubusercontent.com/8824708/268362931-d28aa192-4b38-4c48-9f80-abcbd15df858.png">

hmmmmm - maybe it's expecting `management` to be the name and you don't have a cluster with that name. Not sure.

**Comment by joshri** [comment]
> Besides, there is an issue (more prominent on shorter HelmChart suspend button) with the rotating indicator going beyond the Suspend button boundaries:
> 
>  Screen.Recording.2023-09-15.at.20.16.27.mov 
> So, if both of these problems are new, I will create issues for them on Monday.

Yep - hit em with the ui-triage tag

**Comment by opudrovs** [comment]
Re-tested it manually, works fine for me in Chrome. Great job! ✨ 

The only minor issue left is that when selecting and copying a portion of YAML in Firefox, blank lines are inserted between YAML lines.

This is what I see when copy=pasting several lines from Chrome (works as expected):

```
metadata:
  annotations:
    metadata.weave.works/CreatedBy: Value 4
    metadata.weave.works/Version: some version
    metadata.weave.works/created-by: Value 2
    metadata.weave.works/createdBy: Value 3
    metadata.weave.works/description: Value 1
    metadata.weave.works/html: <p><b>html</b></p>
    metadata.weave.works/link-to-google: https://google.com
    metadata.weave.works/multi-lines: |
      This is first line
      This is second line
  creationTimestamp: 2023-09-15T15:03:27Z
  finalizers:
    - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
```

and this is what I see when copy-pasting from Firefox:

```
metadata:

  annotations:

    metadata.weave.works/CreatedBy: Value 4

    metadata.weave.works/Version: some version

    metadata.weave.works/created-by: Value 2

    metadata.weave.works/createdBy: Value 3

    metadata.weave.works/description: Value 1

    metadata.weave.works/html: <p><b>html</b></p>

    metadata.weave.works/link-to-google: https://google.com

    metadata.weave.works/multi-lines: |

      This is first line

      This is second line

  creationTimestamp: 2023-09-15T15:03:27Z

  finalizers:

    - finalizers.fluxcd.io

  generation: 1

  labels:

    kustomize.toolkit.fluxcd.io/name: flux-system

    kustomize.toolkit.fluxcd.io/namespace: flux-system
```

But I think it can be considered a Firefox issue.
