### ISSUE TITLE
Add a default group for all OIDC users

### ISSUE THREAD

**Issue by evandam** [weaveworks/weave-gitops#4104]
**Problem**

When using some OIDC providers (such as Google) with Dex or something similar, it can be tricky to configure mapping groups. For many users, I'm sure granting all OIDC users one "hard-coded" group would suffice and we can create RoleBindings on that group.

Currently, if I can't map my OIDC groups, the only solution seems to be to create RoleBindings for every possible user (evan@company.xyz, alice@company.xyz, bob@company.xyz, etc.).

**Solution**

Add support something like `oidcDefaultGroup=read-only` in the `oidc-auth` secret. This should get passed when making impersonated calls.

**Additional context**

I may be looking at this wrong and there's a better way to do this (maybe on the Dex side?). Happy to hear alternatives or workaround! :raised_hands:

**Comment by bigkevmcd** [comment]
How are you configuring your Kubernetes to handle this?

We have kept to the same nomenclature and functionality as described here https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ 

But that's no reason we couldn't do something like this, but one of the design goals was that debugging auth should be do able using `kubectl auth`.

So, can you say a bit more about how you're configuring your K8s api-server here?

**Comment by evandam** [comment]
Hi @bigkevmcd, thanks for the response - happy to elaborate more.

First, I'm using a Dex connector like this (with correct env vars passed). No groups are passed for my account:

```yaml
connectors:
  - type: google
    id: google
    name: Google
    config:
      clientID: '{{ getenv "GOOGLE_CLIENT_ID" }}'
      clientSecret: '{{ getenv "GOOGLE_CLIENT_SECRET" }}'
      redirectURI: '{{ getenv "DEX_ISSUER_URL" }}/callback'
```

I'm also using `oidUsernamePrefix` and `oidcGroupsPrefix`, but I don't think it matters much either way - just so it's clear where the users/groups are coming from:

```yaml
oidcUsernamePrefix: weave-gitops-
oidcGroupsPrefix: weave-gitops-
```

For the sake of simplicity, I'm then trying to give any user logged in through OIDC the cluster-admin ClusterRoleBinding:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: weave-gitops-oidc-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  # NOTE: I'm able to log in and access everything, but painful doing it one user at a time.
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: weave-gitops-evan@company.xyz
  # TODO: How can I apply a ClusterRoleBinding to all users without a group to reference?
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: weave-gitops-<SOMETHING>
```

Hopefully it makes more sense! I feel like I'm probably missing something obvious but I'm not sure 😅
