### ISSUE TITLE
Allow users/community to define healthy status conditions per kubernetes resources per versions

### ISSUE THREAD

**Issue by Cajga** [weaveworks/weave-gitops#4140]
**Problem**

Currently, weave gitops reports "red" status instead of "green" at graph view for several resource types while the resource is in fact healthy.

Example:
HorizontalPodAutoscaler (apiVersion: autoscaling/v2)
It has 3 [status conditions](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#appendix-horizontal-pod-autoscaler-status-conditions):

- AbleToScale: should be True,
- ScalingActive: should be True,
- ScalingLimited: should be False

**Solution**

Define a way/procedure how/where users/projects can define the healthy status of a resource on a specific version. It could be a configuration or sending a PR etc.

**Additional context**

I would be willing to contribute the definition of several resources if it would be well defined how to do it

**Comment by makkes** [comment]
To determine the health of HPAs Weave GitOps [compares](https://github.com/weaveworks/weave-gitops/blob/b9493a86f0b73eab217aa43100a50cb5ee5b2948/pkg/health/health.go#L250) `.status.currentReplicas` with `.status.desiredReplicas` and [checks each existing condition](https://github.com/weaveworks/weave-gitops/blob/b9493a86f0b73eab217aa43100a50cb5ee5b2948/pkg/health/health.go#L319) for a "Failed" or "Invalid" reason.

@Cajga would you mind posting the complete `.status` object of your HPA here?

```
kubectl get hpa -n NAMESPACE HPA -o jsonpath={.status}
```

**Comment by Cajga** [comment]
@makkes thanks for looking into this. Sure, here we are:
```yaml
# kubectl get hpa -n istio-system istiod -o jsonpath={.status}|jq
{
  "conditions": [
    {
      "lastTransitionTime": "2023-11-17T15:15:50Z",
      "message": "recent recommendations were higher than current one, applying the highest recent recommendation",
      "reason": "ScaleDownStabilized",
      "status": "True",
      "type": "AbleToScale"
    },
    {
      "lastTransitionTime": "2023-11-17T15:16:20Z",
      "message": "the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)",
      "reason": "ValidMetricFound",
      "status": "True",
      "type": "ScalingActive"
    },
    {
      "lastTransitionTime": "2023-11-18T19:10:45Z",
      "message": "the desired count is within the acceptable range",
      "reason": "DesiredWithinRange",
      "status": "False",
      "type": "ScalingLimited"
    }
  ],
  "currentMetrics": [
    {
      "resource": {
        "current": {
          "averageUtilization": 0,
          "averageValue": "3m"
        },
        "name": "cpu"
      },
      "type": "Resource"
    }
  ],
  "currentReplicas": 1,
  "desiredReplicas": 1
}
```
