### ISSUE TITLE
OIDC with custom CA not usable

### ISSUE THREAD

**Issue by lusor** [weaveworks/weave-gitops#4173]
**Describe the bug**

I am trying to use OIDC with Weave Gitops, however due to my identity server having a custom/self-signed SSL certificate, Gitops cannot connect to the IdP and terminates.
I could not find any way to let Gitops use a custom CA, either by passing an additional argument or via the helm chart.

**Environment**

- Weave-Gitops: 0.38.0
- Flux: irrelevant
- Kubernetes: irrelevant

**To Reproduce**

Configure `issuerURL` in secret `oidc-auth` to an HTTPS service which is configured with a custom/self-signed certificate and start/restart the Gitops pod.

**Expected behavior**

There is a way to provide a custom CA file for Gitops to trust

**Actual Behavior**

Gitops pod terminates because it does not trust the certificate of the IdP.

**Comment by bigkevmcd** [comment]
We are going to provide a simple way to do this, but you can customise a HelmRelease with a post-render

```yaml
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: weave-gitops-enterprise-mccp-cluster-service
              namespace: flux-system
            spec:
              template:
                spec:
                  containers:
                    - name: clusters-service
                      volumeMounts:
                        - mountPath: /usr/local/share/ca-certificates
                          name: custom-ca
                      env:
                        - name: SSL_CERT_FILE
                          value: /usr/local/share/ca-certificates/ca-bundle.crt
                  volumes:
                    - configMap:
                        defaultMode: 420
                        name: custom-ca
                      name: custom-ca
```
