### ISSUE TITLE
Allow setting impersonation extras

### ISSUE THREAD

**Issue by waterfoul** [weaveworks/weave-gitops#4189]
**Problem**
When an aks cluster is setup with EntraId Auth and Azure RBAC you need to pass "extra:oid" in order for impersonation to work. This means weave gitops' impersonation will not work. Example:

```
kubectl get GitRepository -A --as "user@domain.com"
```
Results in
```
Error from server (Forbidden): gitrepositories.source.toolkit.fluxcd.io is forbidden: User "user@domain.com" cannot list resource "gitrepositories" in API group "source.toolkit.fluxcd.io" at the cluster scope: Azure does not have opinion for this non AAD user. If you are an AAD user, please set Extra:oid parameter for impersonated user in the kubeconfig
```
If you create a user in your kubeconfig with
```
  user:
    as: user@domain.com
    as-user-extra:
      oid:
      - 00000000-0000-0000-0000-000000000000
```
along with the normal user config and use it the (via a new context) it works

**Solution**
I'd like a feature to be able to map oidc claims to impersonation extras

**Additional context**
