### ISSUE TITLE
ww-gitops status not ready

### ISSUE THREAD

**Issue by adamcirillo** [weaveworks/weave-gitops#4698]
**Describe the bug**
i've used the cli to create the config for gitops and installed it. In the ui here the status of ww-gitops is not ready. it seems this is related to not using an OCI Repository that causes this, I've made the changes in the 2nd yaml i provided below and this has fixed the problem. i had to add the image tag in there as well since it was pulling 0.38 the cli version i downloaded was 0.39.0-rc1
![Image](https://github.com/user-attachments/assets/0918b6aa-a91b-4d39-875d-847022aa6c1b)

![Image](https://github.com/user-attachments/assets/e1e1c342-7c87-489f-be67-eb9e522f15cb)

**Environment**

- Weave-Gitops Version 0.39.0-rc1
- Flux Version 2.4.0
- Kubernetes version 1.32.1

**To Reproduce**

login to dashboard and click status see screenshoot

**Expected behavior**

**Actual Behavior**

**Additional Context (screenshots, logs, etc)**
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  annotations:
    metadata.weave.works/description:
      This is the source location for the Weave GitOps
      Dashboard's helm chart.
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description:
      This is the Weave GitOps Dashboard.  It provides
      a simple way to get insights into your GitOps workloads.
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1h0m0s
  values:
    adminUser:
      create: true
      passwordHash: removed
      username: admin
    image:
      tag: 0.39.0-rc.1
```

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  annotations:
    metadata.weave.works/description:
      This is the source location for the Weave GitOps
      Dashboard's helm chart.
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  url: oci://ghcr.io/weaveworks/charts/weave-gitops
  ref:
    tag: 4.0.36
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: >
      This is the Weave GitOps Dashboard. It provides a simple way to get insights into your GitOps workloads.
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: ww-gitops
  chartRef:
    kind: OCIRepository
    name: ww-gitops
    namespace: flux-system
  values:
    adminUser:
      create: true
      passwordHash: removed
      username: admin
    image:
      tag: 0.39.0-rc.1
```
