### ISSUE TITLE
WeGO does not provide support for user-specified application/workload namespace

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#472]
**Describe the bug**
User cannot specify custom namespace to install applications. In a scenario where the user specifies a namespace for wego-automation AND provides _another_ namespace for workloads, the command would look something like this:

`wego app add --app-config-url=<url> --namespace=<wego-automation> --namespace<workloadNamespace>`

This is confusing from a user's perspective. A better option would be to allow support for installation of apps under user-specified namespace.

**To Reproduce**
1. Download wego
2. `wego gitops install --namespace=<wego-automation>`
3. `wego add app --url=<helmRepoUrl> --chart=<chart> --app-config-url=<url> --namespace<workloadNamespace> --namespace=<wego-automation>`

**Comment by jpellizzari** [comment]
@rokshana-b What should happen if I specify a `deployment` with a namespace of `foo` in the deployment yaml:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: foo <= I have a namespace specified in the yaml
```
