### ISSUE TITLE
Add first round of RBAC files to give wego-api permissions within the cluster and install them on `wego gitops install`

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#651]
**Short description**
As a developer I want to add and install rbac yaml files so that `wego-api` can only access the resources it needs within the cluster.

```
something
```

Files necessary are:
- ServiceAccount
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: wego-system
secrets:
  - name: api-service-account-token
```

- Deployment **( This is not necessary right now, there is another ticket for it)**
- Role
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: wego-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","create"]

Not sure what is the right alignment for these:

resources: ["apps.wego.weave.works"]
verbs: ["get","create","list","delete","watch"]

resources: ["kustomizations.kustomize.toolkit.fluxcd.io"]
verbs: ["get","create","delete","list"]

resources: ["helmreleases.helm.toolkit.fluxcd.io"]
verbs: ["get","create","delete","list"]

resources: ["helmrepositories.source.toolkit.fluxcd.io"]
verbs: ["get","create","delete","list"]

resources: ["gitrepositories.source.toolkit.fluxcd.io"]
verbs: ["get","create","delete","list"]

```
- RoleBinding
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: wego-system
subjects:
  - kind: ServiceAccount
    name: api-service-account
    namespace: wego-system
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
```
- Service **( This is not necessary right now, there is another ticket for it)**

This resource must be installed when running `wego gitops install`.

**Acceptance criteria**
- [ ] _does X_
- [ ] _displays Y_
- [ ] _..._

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._
