### ISSUE TITLE
Create wego-app yamls and apply them on `gitops install`

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#655]
We need to generate the k8s resources for `wego-app` to run as a permanent resident on the cluster.

A very important step here is to tell which `wego-app` tag it will be used in the Deployment resource. For that we might need to add the Deployment programmatically as we need to inject which tag of wego-app it will use. For production we will use use the `version` LD flag.

Acceptance Criteria:
* Apply the RBAC roles laid out below
* Apply the service and deployment yamls
* Ensure that the correct docker image tag is specified in the Deployment pod spec
* `$ kubectl get pods -n wego-system` should return the `wego-app` pod
* HTTP requests should be possible once the `wego-app` pod is ready
* On dry-run, it should output yamls to stdout
* This command should be idempotent

Note that these yamls may need to be tweaked.

Resources:
- Deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wego-app
  namespace: wego-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wego-app
    spec:
      serviceAccountName: wego-api-service-account
      containers:
        - name: wego-app
          image: ghcr.io/weaveworks/weave-gitops:v0.2.4
          ports:
            - containerPort: 8283
          imagePullPolicy: IfNotPresent
```
- Service
```
apiVersion: v1
kind: Service
metadata:
  name: wego-app
  namespace: wego-system
spec:
  selector:
    app: wego-app
  ports:
    - protocol: TCP
      port: 8283
      targetPort: 8283
```

- ServiceAccount
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wego-app-service-account
  namespace: wego-system
secrets:
  - name: wego-api-service-account-token
```

- Role
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: wego-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","create"]

resources: ["apps.wego.weave.works"]
verbs: ["get","create","list","delete","watch"]

resources: ["kustomizations.kustomize.toolkit.fluxcd.io"]
verbs: ["get","create","delete","list"]

resources: ["helmreleases.helm.toolkit.fluxcd.io"]
verbs: ["get","create","delete","list"]

resources: ["helmrepositories.source.toolkit.fluxcd.io"]
verbs: ["get","create","delete","list"]

resources: ["gitrepositories.source.toolkit.fluxcd.io"]
verbs: ["get","create","delete","list"]

```
- RoleBinding
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: wego-system
subjects:
  - kind: ServiceAccount
    name: wego-app-service-account
    namespace: wego-system
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
```
